## Assignment 2: Follow Mr. Kryaschev's instrutions

#### Extra Credit: Make the function python2 and python3 compatible so that it works on the PUI2016_Python3 Kernel

In [4]:
# use try and except function
# look at HW3_3

# in python 3 use io instead of StringIO
# change urllib3 as urllib.request
import ast
import pandas as pd
import io

try:
    import urllib2 as urlib
except ImportError:
    import urllib.request as urlib

    
try:
    from StringIO import StringIO
except ImportError:
    import io
from io import StringIO


try:
    from urllib import urlencode as urlencode
except ImportError:
    from urllib.parse import urlencode as urlencode
    
try:
    from urllib import urlopen as urlopen
except ImportError:
    from urllib.request import urlopen as urlopen
    
try:
    from urllib2 import HTTPError as HTTPError
except ImportError:
    from urllib.error import HTTPError as HTTPError

In [5]:
# using the same account I used in the lab
SQL_SOURCE = 'https://fb55.carto.com/api/v2/sql?q=SELECT'

# bring document from html 
Citibike_ridership = 'http://serv.cusp.nyu.edu/~hvo/files/citibike.csv'
def queryCartoDB(query, formatting = 'CSV',source =SQL_SOURCE):
    '''queries carto datasets from a given carto account
    Arguments: 
    query - string: a valid sql query string
    format - outlut format  OPTIONAL (default CSV)
    source - a valid sql api endpoint OPTIONAL (default carto fb55 account)
    Returns:
    the return of the sql query AS A STRING
    NOTES:
    designed for the carto API, tested only with CSV return format'''
    
    # urlencode({'format'ï¼šformat,'q':query})
    
    data = urlencode({'format':formatting,'q':query}).encode('utf-8')
    try:
        response = urlopen(source,data)
        return response.read()
    except HTTPError as e:
        raise ValueError('\n',join(ast.literal_eval(e.readline())['Error']))
    except Exception:
        raise
    return response.read()

** for extra credit working in python 3 and python 2

In [6]:
# write a function " get_data " to   pd.read_csv(io(queryCartoDB(query)),sep = ',')

# in python 3 use io.BytesIO instead of StringIO

# python3 use io.BytesIO / python 2 use StringIO.StringIO

def get_data(query):
    try:
        #print("python2")
        return pd.read_csv(StringIO.StringIO(queryCartoDB(query)),sep = ',')
    
    except AttributeError:
        #print("python3")
        return pd.read_csv(io.BytesIO(queryCartoDB(query)),sep = ',')

        
        
# def get_data(query):
#     try:
#         # python2
#         return pd.read_csv(StringIO.StringIO(queryCartoDB(query)),sep = ',')
#     except AttributeError as av:
#         return pd.read_csv(io.BytesIO(queryCartoDB(query)),sep = ',')

In [7]:
test = '''
SELECT *
FROM citibike;
'''

In [8]:
data  = get_data(test)

In [9]:
data

,the_geom,start_station_name,the_geom_webmercator,field_1,start_station_longitude,tripduration,starttime,stoptime,start_station_id,cartodb_id,start_station_latitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,NaN,E 20 St & Park Ave,NaN,175,-73.987520,1090,2015-02-01 01:23:00+00,2015-02-01 01:42:00+00,503,107,40.738274,229,Great Jones St,40.727434,-73.993790,19718,Subscriber,1961.0,1
1,NaN,W 43 St & 10 Ave,NaN,1159,-73.994618,682,2015-02-01 10:55:00+00,2015-02-01 11:07:00+00,515,1088,40.760094,490,8 Ave & W 33 St,40.751551,-73.993934,21501,Subscriber,1981.0,1
2,NaN,E 6 St & Avenue B,NaN,2827,-73.981854,751,2015-02-01 13:59:00+00,2015-02-01 14:11:00+00,317,2759,40.724537,466,W 25 St & 6 Ave,40.743954,-73.991449,14788,Subscriber,1990.0,1
3,NaN,E 12 St & 3 Ave,NaN,4961,-73.988900,272,2015-02-01 17:28:00+00,2015-02-01 17:32:00+00,483,4893,40.732233,345,W 13 St & 6 Ave,40.736494,-73.997044,16219,Subscriber,1961.0,1
4,NaN,W 41 St & 8 Ave,NaN,6156,-73.990026,240,2015-02-01 21:36:00+00,2015-02-01 21:40:00+00,477,6090,40.756405,490,8 Ave & W 33 St,40.751551,-73.993934,18266,Customer,NaN,0
5,NaN,5 Ave & E 29 St,NaN,7433,-73.986831,376,2015-02-02 17:44:00+00,2015-02-02 17:50:00+00,474,7367,40.745168,537,Lexington Ave & E 24 St,40.740259,-73.984092,18048,Subscriber,1977.0,1
6,NaN,Allen St & Hester St,NaN,7779,-73.991908,1217,2015-02-02 20:12:00+00,2015-02-02 20:32:00+00,361,7712,40.716059,461,E 20 St & 2 Ave,40.735877,-73.982050,19732,Customer,NaN,0
7,NaN,E 39 St & 3 Ave,NaN,8327,-73.976049,441,2015-02-03 08:02:00+00,2015-02-03 08:10:00+00,167,8263,40.748901,526,E 33 St & 5 Ave,40.747659,-73.984907,21518,Subscriber,1975.0,1
8,NaN,10 Ave & W 28 St,NaN,9435,-74.001768,1475,2015-02-03 12:31:00+00,2015-02-03 12:56:00+00,489,9375,40.750664,455,1 Ave & E 44 St,40.750020,-73.969053,19863,Subscriber,1984.0,2
9,NaN,E 2 St & 2 Ave,NaN,10472,-73.990697,420,2015-02-03 16:45:00+00,2015-02-03 16:52:00+00,403,10411,40.725029,297,E 15 St & 3 Ave,40.734232,-73.986923,19257,Subscriber,1984.0,1
10,NaN,1 Ave & E 44 St,NaN,10931,-73.969053,876,2015-02-03 17:37:00+00,2015-02-03 17:52:00+00,455,10867,40.750020,477,W 41 St & 8 Ave,40.756405,-73.990026,17392,Subscriber,1977.0,1
11,NaN,W 45 St & 6 Ave,NaN,11361,-73.982912,640,2015-02-03 18:21:00+00,2015-02-03 18:32:00+00,493,11300,40.756800,440,E 45 St & 3 Ave,40.752554,-73.972826,21433,Subscriber,1981.0,1
12,NaN,W 18 St & 6 Ave,NaN,12173,-73.994564,571,2015-02-03 20:26:00+00,2015-02-03 20:35:00+00,168,12114,40.739713,494,W 26 St & 8 Ave,40.747348,-73.997236,19493,Subscriber,1964.0,1
13,NaN,E 58 St & 3 Ave,NaN,12211,-73.967245,821,2015-02-03 20:37:00+00,2015-02-03 20:50:00+00,305,12152,40.760958,515,W 43 St & 10 Ave,40.760094,-73.994618,16564,Subscriber,1983.0,1
14,NaN,E 33 St & 5 Ave,NaN,12560,-73.984907,376,2015-02-03 22:20:00+00,2015-02-03 22:26:00+00,526,12500,40.747659,507,E 25 St & 2 Ave,40.739126,-73.979738,19721,Subscriber,1991.0,1
15,NaN,W 31 St & 7 Ave,NaN,13239,-73.991600,770,2015-02-04 07:21:00+00,2015-02-04 07:34:00+00,379,13183,40.749156,461,E 20 St & 2 Ave,40.735877,-73.982050,15184,Subscriber,1987.0,2
16,NaN,5 Ave & E 29 St,NaN,13365,-73.986831,319,2015-02-04 07:35:00+00,2015-02-04 07:40:00+00,474,13312,40.745168,476,E 31 St & 3 Ave,40.743943,-73.979661,16067,Subscriber,1991.0,1
17,NaN,E 39 St & 2 Ave,NaN,13750,-73.973442,358,2015-02-04 08:11:00+00,2015-02-04 08:17:00+00,518,13702,40.747804,537,Lexington Ave & E 24 St,40.740259,-73.984092,19181,Subscriber,1991.0,1
18,NaN,10 Ave & W 28 St,NaN,14218,-74.001768,338,2015-02-04 08:45:00+00,2015-02-04 08:50:00+00,489,14172,40.750664,494,W 26 St & 8 Ave,40.747348,-73.997236,18840,Subscriber,1992.0,2
19,NaN,W 42 St & 8 Ave,NaN,14431,-73.990985,575,2015-02-04 08:59:00+00,2015-02-04 09:08:00+00,529,14384,40.757570,442,W 27 St & 7 Ave,40.746647,-73.993915,15151,Subscriber,1956.0,1
20,NaN,E 27 St & 1 Ave,NaN,15157,-73.976806,451,2015-02-04 10:10:00+00,2015-02-04 10:17:00+00,2012,15113,40.739445,518,E 39 St & 2 Ave,40.747804,-73.973442,20338,Subscriber,1990.0,2
21,NaN,Great Jones St,NaN,15669,-73.993790,548,2015-02-04 11:51:00+00,2015-02-04 12:00:00+00,229,15625,40.727434,284,Greenwich Ave & 8 Ave,40.739017,-74.002638,15482,Subscriber,1962.0,1
22,NaN,W 49 St & 8 Ave,NaN,16526,-73.987882,404,2015-02-04 14:08:00+00,2015-02-04 14:14:00+00,450,16481,40.762272,520,W 52 St & 5 Ave,40.759923,-73.976485,17488,Subscriber,1965.0,2
23,NaN,Broadway & W 24 St,NaN,16572,-73.989151,357,2015-02-04 14:15:00+00,2015-02-04 14:21:00+00,444,16527,40.742354,475,E 16 St & Irving Pl,40.735243,-73.987586,17453,Subscriber,1975.0,1
24,NaN,E 40 St & 5 Ave,NaN,18931,-73.981632,330,2015-02-04 18:02:00+00,2015-02-04 18:08:00+00,153,18880,40.752062,518,E 39 St & 2 Ave,40.747804,-73.973442,18973,Subscriber,1980.0,1
25,NaN,E 16 St & 5 Ave,NaN,19229,-73.992390,606,2015-02-04 18:19:00+00,2015-02-04 18:29:00+00,496,19177,40.737262,379,W 31 St & 7 Ave,40.749156,-73.991600,18362,Subscriber,1981.0,1
26,NaN,Broadway & W 36 St,NaN,20481,-73.987654,1001,2015-02-04 19:59:00+00,2015-02-04 20:15:00+00,267,20425,40.750977,504,1 Ave & E 15 St,40.732219,-73.981656,19935,Subscriber,1985.0,2
27,NaN,8 Ave & W 31 St,NaN,21285,-73.994811,1618,2015-02-04 21:58:00+00,2015-02-04 22:25:00+00,521,21228,40.750450,483,E 12 St & 3 Ave,40.732233,-73.988900,14660,Subscriber,1976.0,1
28,NaN,W 45 St & 6 Ave,NaN,23338,-73.982912,876,2015-02-05 08:29:00+00,2015-02-05 08:43:00+00,493,23298,40.756800,454,E 51 St & 1 Ave,40.754557,-73.965930,16891,Subscriber,1964.0,1
29,NaN,FDR Drive & E 35 St,NaN,23392,-73.971212,506,2015-02-05 08:32:00+00,2015-02-05 08:40:00+00,501,23353,40.744219,164,E 47 St & 2 Ave,40.753231,-73.970325,18208,Subscriber,1978.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46170,NaN,Washington Pl & Broadway,NaN,46170,-73.994046,812,2015-02-07 23:51:00+00,2015-02-08 00:05:00+00,335,46171,40.729039,435,W 21 St & 6 Ave,40.741740,-73.994156,15733,Subscriber,1988.0,1
46171,NaN,Allen St & Hester St,NaN,46171,-73.991908,647,2015-02-07 23:51:00+00,2015-02-08 00:02:00+00,361,46172,40.716059,504,1 Ave & E 15 St,40.732219,-73.981656,16931,Subscriber,1995.0,1
46172,NaN,Warren St & Church St,NaN,46172,-74.009106,563,2015-02-07 23:51:00+00,2015-02-08 00:00:00+00,152,46173,40.714740,401,Allen St & Rivington St,40.720196,-73.989978,17202,Subscriber,1987.0,1
46173,NaN,E 12 St & 3 Ave,NaN,46173,-73.988900,470,2015-02-07 23:51:00+00,2015-02-07 23:59:00+00,483,46174,40.732233,439,E 4 St & 2 Ave,40.726281,-73.989780,20314,Subscriber,1989.0,2
46174,NaN,Dean St & 4 Ave,NaN,46174,-73.978951,299,2015-02-07 23:51:00+00,2015-02-07 23:56:00+00,467,46175,40.683125,395,Bond St & Schermerhorn St,40.688070,-73.984106,21531,Subscriber,1989.0,1
46175,NaN,Allen St & Hester St,NaN,46175,-73.991908,629,2015-02-07 23:52:00+00,2015-02-08 00:02:00+00,361,46176,40.716059,504,1 Ave & E 15 St,40.732219,-73.981656,21491,Subscriber,1968.0,1
46176,NaN,Broadway & E 22 St,NaN,46176,-73.989551,499,2015-02-07 23:52:00+00,2015-02-08 00:00:00+00,402,46177,40.740343,380,W 4 St & 7 Ave S,40.734011,-74.002939,15367,Subscriber,1990.0,1
46177,NaN,Washington Pl & 6 Ave,NaN,46177,-74.000264,474,2015-02-07 23:52:00+00,2015-02-08 00:00:00+00,369,46178,40.732241,368,Carmine St & 6 Ave,40.730386,-74.002150,18978,Subscriber,1973.0,2
46178,NaN,E 31 St & 3 Ave,NaN,46178,-73.979661,345,2015-02-07 23:52:00+00,2015-02-07 23:58:00+00,476,46179,40.743943,504,1 Ave & E 15 St,40.732219,-73.981656,19507,Subscriber,1980.0,1
46179,NaN,Broadway & W 60 St,NaN,46179,-73.981918,829,2015-02-07 23:53:00+00,2015-02-08 00:07:00+00,499,46180,40.769155,160,E 37 St & Lexington Ave,40.748238,-73.978311,16936,Subscriber,1980.0,1
46180,NaN,Carmine St & 6 Ave,NaN,46180,-74.002150,776,2015-02-07 23:53:00+00,2015-02-08 00:05:00+00,368,46181,40.730386,531,Forsyth St & Broome St,40.718939,-73.992663,18689,Subscriber,1982.0,1
46181,NaN,W 52 St & 5 Ave,NaN,46181,-73.976485,697,2015-02-07 23:53:00+00,2015-02-08 00:05:00+00,520,46182,40.759923,478,11 Ave & W 41 St,40.760301,-73.998842,15781,Subscriber,1972.0,1
46182,NaN,Dean St & 4 Ave,NaN,46182,-73.978951,1703,2015-02-07 23:54:00+00,2015-02-08 00:23:00+00,467,46183,40.683125,471,Grand St & Havemeyer St,40.712868,-73.956981,15081,Subscriber,1988.0,1
46183,NaN,9 Ave & W 45 St,NaN,46183,-73.991255,922,2015-02-07 23:54:00+00,2015-02-08 00:10:00+00,479,46184,40.760193,247,Perry St & Bleecker St,40.735354,-74.004831,21672,Subscriber,1983.0,1
46184,NaN,Broadway & W 58 St,NaN,46184,-73.981693,849,2015-02-07 23:54:00+00,2015-02-08 00:08:00+00,457,46185,40.766953,488,W 39 St & 9 Ave,40.756458,-73.993722,16336,Subscriber,1970.0,1
46185,NaN,Broadway & W 58 St,NaN,46185,-73.981693,826,2015-02-07 23:54:00+00,2015-02-08 00:08:00+00,457,46186,40.766953,488,W 39 St & 9 Ave,40.756458,-73.993722,21609,Subscriber,1973.0,1
46186,NaN,Watts St & Greenwich St,NaN,46186,-74.009660,473,2015-02-07 23:54:00+00,2015-02-08 00:02:00+00,328,46187,40.724055,3002,South End Ave & Liberty St,40.711512,-74.015756,19470,Subscriber,1964.0,1
46187,NaN,W 51 St & 6 Ave,NaN,46187,-73.980420,332,2015-02-07 23:54:00+00,2015-02-07 23:59:00+00,510,46188,40.760660,450,W 49 St & 8 Ave,40.762272,-73.987882,18167,Subscriber,1960.0,1
46188,NaN,University Pl & E 14 St,NaN,46188,-73.992005,456,2015-02-07 23:55:00+00,2015-02-08 00:03:00+00,382,46189,40.734927,404,9 Ave & W 14 St,40.740583,-74.005509,15929,Subscriber,1987.0,1
46189,NaN,W 11 St & 6 Ave,NaN,46189,-73.998004,327,2015-02-07 23:55:00+00,2015-02-08 00:01:00+00,254,46190,40.735324,466,W 25 St & 6 Ave,40.743954,-73.991449,17541,Subscriber,1983.0,1
46190,NaN,W 17 St & 8 Ave,NaN,46190,-74.001497,306,2015-02-07 23:55:00+00,2015-02-08 00:01:00+00,116,46191,40.741776,494,W 26 St & 8 Ave,40.747348,-73.997236,14736,Subscriber,1983.0,2
46191,NaN,W 47 St & 10 Ave,NaN,46191,-73.993012,1248,2015-02-07 23:56:00+00,2015-02-08 00:17:00+00,495,46192,40.762699,432,E 7 St & Avenue A,40.726218,-73.983799,16300,Subscriber,1984.0,1
46192,NaN,Warren St & Church St,NaN,46192,-74.009106,1165,2015-02-07 23:56:00+00,2015-02-08 00:15:00+00,152,46193,40.714740,325,E 19 St & 3 Ave,40.736245,-73.984738,16978,Subscriber,1959.0,1
46193,NaN,E 20 St & 2 Ave,NaN,46193,-73.982050,993,2015-02-07 23:56:00+00,2015-02-08 00:13:00+00,461,46194,40.735877,295,Pike St & E Broadway,40.714067,-73.992939,16722,Subscriber,1974.0,1
46194,NaN,1 Ave & E 44 St,NaN,46194,-73.969053,1422,2015-02-07 23:57:00+00,2015-02-08 00:20:00+00,455,46195,40.750020,265,Stanton St & Chrystie St,40.722293,-73.991475,20184,Subscriber,1960.0,2
46195,NaN,W 20 St & 8 Ave,NaN,46195,-74.000040,689,2015-02-07 23:57:00+00,2015-02-08 00:08:00+00,470,46196,40.743453,325,E 19 St & 3 Ave,40.736245,-73.984738,15585,Subscriber,1953.0,1
46196,NaN,5 Ave & E 29 St,NaN,46196,-73.986831,428,2015-02-07 23:57:00+00,2015-02-08 00:04:00+00,474,46197,40.745168,325,E 19 St & 3 Ave,40.736245,-73.984738,16395,Subscriber,1986.0,2
46197,NaN,5 Ave & E 29 St,NaN,46197,-73.986831,392,2015-02-07 23:57:00+00,2015-02-08 00:03:00+00,474,46198,40.745168,325,E 19 St & 3 Ave,40.736245,-73.984738,15545,Subscriber,1986.0,1
46198,NaN,Carmine St & 6 Ave,NaN,46198,-74.002150,548,2015-02-07 23:58:00+00,2015-02-08 00:08:00+00,368,46199,40.730386,334,W 20 St & 7 Ave,40.742388,-73.997262,19540,Subscriber,1983.0,2
46199,NaN,E 4 St & 2 Ave,NaN,46199,-73.989780,917,2015-02-07 23:59:00+00,2015-02-08 00:15:00+00,439,46200,40.726281,417,Barclay St & Church St,40.712912,-74.010202,20998,Subscriber,1965.0,2

In [11]:
# the total rows
len(data.index)

46200

## Follow the  Introduction - to -SQL Lab (through CARTO) Huy T. Vo

# Task 1 - Familiarize with SQL Clauses

**1.Sort data by start_station_id,tription only checking trips with duration <=3 hour**

In [10]:

# rewrite in SQL
# sort data by start_station_id ASC with duration less than 3 hour
test1_1 = '''
SELECT * 
FROM citibike
WHERE tripduration <= 10800
ORDER BY start_station_id ASC
;
'''
table = get_data(test1_1)
table

,the_geom,start_station_name,the_geom_webmercator,field_1,start_station_longitude,tripduration,starttime,stoptime,start_station_id,cartodb_id,start_station_latitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,NaN,W 52 St & 11 Ave,NaN,36425,-73.993929,747,2015-02-06 17:11:00+00,2015-02-06 17:24:00+00,72,36397,40.767272,453,W 22 St & 8 Ave,40.744751,-73.999154,17274,Subscriber,1970.0,1
1,NaN,W 52 St & 11 Ave,NaN,31682,-73.993929,388,2015-02-06 07:53:00+00,2015-02-06 08:00:00+00,72,31639,40.767272,529,W 42 St & 8 Ave,40.757570,-73.990985,16405,Subscriber,1978.0,1
2,NaN,W 52 St & 11 Ave,NaN,40774,-73.993929,1127,2015-02-07 10:41:00+00,2015-02-07 10:59:00+00,72,40761,40.767272,382,University Pl & E 14 St,40.734927,-73.992005,20239,Subscriber,1970.0,1
3,NaN,W 52 St & 11 Ave,NaN,9802,-73.993929,1535,2015-02-03 14:23:00+00,2015-02-03 14:48:00+00,72,9742,40.767272,334,W 20 St & 7 Ave,40.742388,-73.997262,15117,Subscriber,1956.0,2
4,NaN,W 52 St & 11 Ave,NaN,29612,-73.993929,586,2015-02-05 19:07:00+00,2015-02-05 19:16:00+00,72,29569,40.767272,503,E 20 St & Park Ave,40.738274,-73.987520,14700,Subscriber,1993.0,1
5,NaN,W 52 St & 11 Ave,NaN,11259,-73.993929,1074,2015-02-03 18:12:00+00,2015-02-03 18:29:00+00,72,11198,40.767272,367,E 53 St & Lexington Ave,40.758281,-73.970694,21021,Subscriber,1964.0,1
6,NaN,W 52 St & 11 Ave,NaN,13845,-73.993929,517,2015-02-04 08:18:00+00,2015-02-04 08:26:00+00,72,13797,40.767272,520,W 52 St & 5 Ave,40.759923,-73.976485,14918,Subscriber,1977.0,1
7,NaN,W 52 St & 11 Ave,NaN,20040,-73.993929,373,2015-02-04 19:16:00+00,2015-02-04 19:22:00+00,72,19984,40.767272,450,W 49 St & 8 Ave,40.762272,-73.987882,20119,Subscriber,1981.0,1
8,NaN,W 52 St & 11 Ave,NaN,15569,-73.993929,1054,2015-02-04 11:34:00+00,2015-02-04 11:52:00+00,72,15525,40.767272,470,W 20 St & 8 Ave,40.743453,-74.000040,15621,Subscriber,1954.0,2
9,NaN,W 52 St & 11 Ave,NaN,15516,-73.993929,869,2015-02-04 11:22:00+00,2015-02-04 11:37:00+00,72,15472,40.767272,212,W 16 St & The High Line,40.743349,-74.006818,17219,Subscriber,1980.0,2
10,NaN,W 52 St & 11 Ave,NaN,19994,-73.993929,971,2015-02-04 19:12:00+00,2015-02-04 19:28:00+00,72,19939,40.767272,463,9 Ave & W 16 St,40.742065,-74.004432,20188,Subscriber,1984.0,1
11,NaN,W 52 St & 11 Ave,NaN,11301,-73.993929,1518,2015-02-03 18:16:00+00,2015-02-03 18:42:00+00,72,11240,40.767272,476,E 31 St & 3 Ave,40.743943,-73.979661,19039,Subscriber,1971.0,1
12,NaN,W 52 St & 11 Ave,NaN,28936,-73.993929,889,2015-02-05 18:17:00+00,2015-02-05 18:32:00+00,72,28893,40.767272,477,W 41 St & 8 Ave,40.756405,-73.990026,14857,Subscriber,1965.0,1
13,NaN,W 52 St & 11 Ave,NaN,9553,-73.993929,348,2015-02-03 13:01:00+00,2015-02-03 13:06:00+00,72,9494,40.767272,478,11 Ave & W 41 St,40.760301,-73.998842,16754,Subscriber,1961.0,1
14,NaN,W 52 St & 11 Ave,NaN,41118,-73.993929,897,2015-02-07 11:32:00+00,2015-02-07 11:47:00+00,72,41105,40.767272,334,W 20 St & 7 Ave,40.742388,-73.997262,16106,Subscriber,1969.0,1
15,NaN,W 52 St & 11 Ave,NaN,9254,-73.993929,388,2015-02-03 11:23:00+00,2015-02-03 11:30:00+00,72,9194,40.767272,500,Broadway & W 51 St,40.762288,-73.983362,17196,Subscriber,1980.0,1
16,NaN,W 52 St & 11 Ave,NaN,19922,-73.993929,532,2015-02-04 19:06:00+00,2015-02-04 19:15:00+00,72,19867,40.767272,469,Broadway & W 53 St,40.763441,-73.982681,19653,Subscriber,1978.0,1
17,NaN,W 52 St & 11 Ave,NaN,42157,-73.993929,668,2015-02-07 13:58:00+00,2015-02-07 14:09:00+00,72,42147,40.767272,521,8 Ave & W 31 St,40.750450,-73.994811,14918,Subscriber,1983.0,1
18,NaN,W 52 St & 11 Ave,NaN,42447,-73.993929,551,2015-02-07 14:33:00+00,2015-02-07 14:42:00+00,72,42438,40.767272,499,Broadway & W 60 St,40.769155,-73.981918,18527,Subscriber,1981.0,1
19,NaN,W 52 St & 11 Ave,NaN,35523,-73.993929,928,2015-02-06 15:53:00+00,2015-02-06 16:08:00+00,72,35492,40.767272,472,E 32 St & Park Ave,40.745712,-73.981948,18606,Subscriber,1972.0,1
20,NaN,W 52 St & 11 Ave,NaN,718,-73.993929,344,2015-02-01 09:49:00+00,2015-02-01 09:54:00+00,72,649,40.767272,2021,W 45 St & 8 Ave,40.759291,-73.988597,14692,Subscriber,1986.0,2
21,NaN,W 52 St & 11 Ave,NaN,20124,-73.993929,574,2015-02-04 19:24:00+00,2015-02-04 19:33:00+00,72,20070,40.767272,352,W 56 St & 6 Ave,40.763406,-73.977225,17997,Subscriber,1974.0,1
22,NaN,W 52 St & 11 Ave,NaN,15305,-73.993929,712,2015-02-04 10:38:00+00,2015-02-04 10:50:00+00,72,15261,40.767272,352,W 56 St & 6 Ave,40.763406,-73.977225,19906,Subscriber,1972.0,2
23,NaN,W 52 St & 11 Ave,NaN,44795,-73.993929,345,2015-02-07 18:46:00+00,2015-02-07 18:51:00+00,72,44789,40.767272,447,8 Ave & W 52 St,40.763707,-73.985162,17669,Subscriber,1983.0,1
24,NaN,W 52 St & 11 Ave,NaN,27144,-73.993929,386,2015-02-05 16:00:00+00,2015-02-05 16:06:00+00,72,27104,40.767272,479,9 Ave & W 45 St,40.760193,-73.991255,15927,Subscriber,1973.0,1
25,NaN,W 52 St & 11 Ave,NaN,13695,-73.993929,1537,2015-02-04 08:07:00+00,2015-02-04 08:33:00+00,72,13647,40.767272,487,E 20 St & FDR Drive,40.733143,-73.975739,18900,Subscriber,1977.0,2
26,NaN,W 52 St & 11 Ave,NaN,20364,-73.993929,1493,2015-02-04 19:47:00+00,2015-02-04 20:12:00+00,72,20309,40.767272,79,Franklin St & W Broadway,40.719116,-74.006667,21080,Subscriber,1964.0,1
27,NaN,W 52 St & 11 Ave,NaN,25882,-73.993929,377,2015-02-05 12:55:00+00,2015-02-05 13:01:00+00,72,25842,40.767272,500,Broadway & W 51 St,40.762288,-73.983362,16310,Subscriber,1972.0,2
28,NaN,W 52 St & 11 Ave,NaN,14586,-73.993929,871,2015-02-04 09:11:00+00,2015-02-04 09:26:00+00,72,14540,40.767272,458,11 Ave & W 27 St,40.751396,-74.005226,20065,Subscriber,1990.0,1
29,NaN,W 52 St & 11 Ave,NaN,2051,-73.993929,1944,2015-02-01 12:39:00+00,2015-02-01 13:12:00+00,72,1983,40.767272,328,Watts St & Greenwich St,40.724055,-74.009660,17849,Customer,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46121,NaN,South End Ave & Liberty St,NaN,23159,-74.015756,388,2015-02-05 08:19:00+00,2015-02-05 08:25:00+00,3002,23119,40.711512,534,Water - Whitehall Plaza,40.702551,-74.012723,17658,Subscriber,1967.0,1
46122,NaN,South End Ave & Liberty St,NaN,5327,-74.015756,838,2015-02-01 18:06:00+00,2015-02-01 18:20:00+00,3002,5261,40.711512,327,Vesey Pl & River Terrace,40.715338,-74.016584,20637,Subscriber,1972.0,1
46123,NaN,South End Ave & Liberty St,NaN,6280,-74.015756,452,2015-02-01 22:22:00+00,2015-02-01 22:29:00+00,3002,6213,40.711512,249,Harrison St & Hudson St,40.718710,-74.009001,18155,Subscriber,1990.0,1
46124,NaN,South End Ave & Liberty St,NaN,3911,-74.015756,181,2015-02-01 15:47:00+00,2015-02-01 15:50:00+00,3002,3844,40.711512,2008,Little West St & 1 Pl,40.705693,-74.016777,20876,Subscriber,1984.0,1
46125,NaN,South End Ave & Liberty St,NaN,46022,-74.015756,329,2015-02-07 23:03:00+00,2015-02-07 23:08:00+00,3002,46023,40.711512,146,Hudson St & Reade St,40.716250,-74.009106,14613,Subscriber,1984.0,1
46126,NaN,South End Ave & Liberty St,NaN,27243,-74.015756,1977,2015-02-05 16:11:00+00,2015-02-05 16:44:00+00,3002,27203,40.711512,318,E 43 St & Vanderbilt Ave,40.753202,-73.977987,20069,Subscriber,1969.0,1
46127,NaN,South End Ave & Liberty St,NaN,43266,-74.015756,1087,2015-02-07 16:01:00+00,2015-02-07 16:19:00+00,3002,43258,40.711512,459,W 20 St & 11 Ave,40.746745,-74.007756,19500,Subscriber,1991.0,1
46128,NaN,South End Ave & Liberty St,NaN,35381,-74.015756,1445,2015-02-06 15:38:00+00,2015-02-06 16:02:00+00,3002,35349,40.711512,334,W 20 St & 7 Ave,40.742388,-73.997262,17077,Subscriber,1956.0,1
46129,NaN,South End Ave & Liberty St,NaN,29574,-74.015756,251,2015-02-05 19:04:00+00,2015-02-05 19:09:00+00,3002,29531,40.711512,2008,Little West St & 1 Pl,40.705693,-74.016777,20663,Subscriber,1980.0,1
46130,NaN,South End Ave & Liberty St,NaN,2271,-74.015756,790,2015-02-01 13:01:00+00,2015-02-01 13:14:00+00,3002,2205,40.711512,368,Carmine St & 6 Ave,40.730386,-74.002150,17004,Subscriber,1979.0,1
46131,NaN,South End Ave & Liberty St,NaN,42793,-74.015756,834,2015-02-07 15:11:00+00,2015-02-07 15:25:00+00,3002,42784,40.711512,355,Bayard St & Baxter St,40.716021,-73.999744,19434,Subscriber,1959.0,1
46132,NaN,South End Ave & Liberty St,NaN,29570,-74.015756,298,2015-02-05 19:04:00+00,2015-02-05 19:08:00+00,3002,29527,40.711512,2008,Little West St & 1 Pl,40.705693,-74.016777,20598,Subscriber,1978.0,2
46133,NaN,South End Ave & Liberty St,NaN,29569,-74.015756,365,2015-02-05 19:04:00+00,2015-02-05 19:10:00+00,3002,29526,40.711512,304,Broadway & Battery Pl,40.704633,-74.013617,16178,Subscriber,1997.0,1
46134,NaN,South End Ave & Liberty St,NaN,31716,-74.015756,243,2015-02-06 07:55:00+00,2015-02-06 07:59:00+00,3002,31673,40.711512,363,West Thames St,40.708347,-74.017134,20605,Subscriber,1958.0,2
46135,NaN,South End Ave & Liberty St,NaN,17650,-74.015756,403,2015-02-04 16:34:00+00,2015-02-04 16:41:00+00,3002,17603,40.711512,320,Leonard St & Church St,40.717571,-74.005549,20348,Subscriber,1975.0,1
46136,NaN,South End Ave & Liberty St,NaN,11313,-74.015756,191,2015-02-03 18:16:00+00,2015-02-03 18:19:00+00,3002,11252,40.711512,327,Vesey Pl & River Terrace,40.715338,-74.016584,15171,Subscriber,1970.0,2
46137,NaN,South End Ave & Liberty St,NaN,16699,-74.015756,841,2015-02-04 14:32:00+00,2015-02-04 14:46:00+00,3002,16654,40.711512,358,Christopher St & Greenwich St,40.732916,-74.007114,17180,Subscriber,1956.0,1
46138,NaN,South End Ave & Liberty St,NaN,2434,-74.015756,1666,2015-02-01 13:18:00+00,2015-02-01 13:46:00+00,3002,2368,40.711512,478,11 Ave & W 41 St,40.760301,-73.998842,16918,Customer,NaN,0
46139,NaN,South End Ave & Liberty St,NaN,33497,-74.015756,253,2015-02-06 10:39:00+00,2015-02-06 10:43:00+00,3002,33463,40.711512,2008,Little West St & 1 Pl,40.705693,-74.016777,17483,Subscriber,1981.0,1
46140,NaN,South End Ave & Liberty St,NaN,23889,-74.015756,466,2015-02-05 08:56:00+00,2015-02-05 09:03:00+00,3002,23851,40.711512,329,Greenwich St & N Moore St,40.720434,-74.010206,21588,Subscriber,1979.0,1
46141,NaN,South End Ave & Liberty St,NaN,12230,-74.015756,170,2015-02-03 20:40:00+00,2015-02-03 20:43:00+00,3002,12171,40.711512,363,West Thames St,40.708347,-74.017134,16155,Subscriber,1979.0,1
46142,NaN,South End Ave & Liberty St,NaN,24252,-74.015756,1823,2015-02-05 09:20:00+00,2015-02-05 09:50:00+00,3002,24214,40.711512,449,W 52 St & 9 Ave,40.764618,-73.987895,16496,Subscriber,1981.0,1
46143,NaN,South End Ave & Liberty St,NaN,30778,-74.015756,320,2015-02-05 23:01:00+00,2015-02-05 23:06:00+00,3002,30732,40.711512,264,Maiden Ln & Pearl St,40.707065,-74.007319,14558,Subscriber,1990.0,1
46144,NaN,South End Ave & Liberty St,NaN,22447,-74.015756,1312,2015-02-05 07:26:00+00,2015-02-05 07:48:00+00,3002,22399,40.711512,459,W 20 St & 11 Ave,40.746745,-74.007756,17198,Subscriber,1991.0,1
46145,NaN,South End Ave & Liberty St,NaN,28924,-74.015756,215,2015-02-05 18:15:00+00,2015-02-05 18:19:00+00,3002,28881,40.711512,327,Vesey Pl & River Terrace,40.715338,-74.016584,17658,Subscriber,1965.0,1
46146,NaN,South End Ave & Liberty St,NaN,1402,-74.015756,1243,2015-02-01 11:27:00+00,2015-02-01 11:48:00+00,3002,1333,40.711512,360,William St & Pine St,40.707179,-74.008873,18288,Customer,NaN,0
46147,NaN,South End Ave & Liberty St,NaN,43925,-74.015756,394,2015-02-07 17:05:00+00,2015-02-07 17:12:00+00,3002,43918,40.711512,147,Greenwich St & Warren St,40.715422,-74.011220,17202,Subscriber,1984.0,1
46148,NaN,South End Ave & Liberty St,NaN,20505,-74.015756,291,2015-02-04 20:01:00+00,2015-02-04 20:06:00+00,3002,20449,40.711512,327,Vesey Pl & River Terrace,40.715338,-74.016584,18272,Subscriber,1935.0,1
46149,NaN,South End Ave & Liberty St,NaN,44784,-74.015756,179,2015-02-07 18:44:00+00,2015-02-07 18:47:00+00,3002,44778,40.711512,327,Vesey Pl & River Terrace,40.715338,-74.016584,21366,Subscriber,1973.0,1
46150,NaN,South End Ave & Liberty St,NaN,361,-74.015756,301,2015-02-01 07:49:00+00,2015-02-01 07:54:00+00,3002,293,40.711512,417,Barclay St & Church St,40.712912,-74.010202,19484,Subscriber,1980.0,2

In [12]:
# rewrite in SQL
# sort data by start_station_id ASC with duration less than 3 hour
test1_1 = '''
SELECT * 
FROM citibike
WHERE tripduration < 10800
ORDER BY tripduration DESC
;
'''
table = get_data(test1_1)
table

,the_geom,start_station_name,the_geom_webmercator,field_1,start_station_longitude,tripduration,starttime,stoptime,start_station_id,cartodb_id,start_station_latitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,NaN,Greenwich Ave & 8 Ave,NaN,41403,-74.002638,10757,2015-02-07 12:17:00+00,2015-02-07 15:16:00+00,284,41392,40.739017,173,Broadway & W 49 St,40.760647,-73.984427,15082,Subscriber,1973.0,1
1,NaN,W 29 St & 9 Ave,NaN,10975,-73.998393,10660,2015-02-03 17:42:00+00,2015-02-03 20:40:00+00,512,10912,40.750073,435,W 21 St & 6 Ave,40.741740,-73.994156,16099,Subscriber,1950.0,1
2,NaN,Washington St & Gansevoort St,NaN,40237,-74.008119,10174,2015-02-07 09:31:00+00,2015-02-07 12:20:00+00,405,40221,40.739323,405,Washington St & Gansevoort St,40.739323,-74.008119,21323,Subscriber,1983.0,1
3,NaN,Centre St & Worth St,NaN,7538,-74.002345,9969,2015-02-02 18:22:00+00,2015-02-02 21:08:00+00,386,7472,40.714948,264,Maiden Ln & Pearl St,40.707065,-74.007319,19921,Subscriber,1987.0,2
4,NaN,Broadway & W 55 St,NaN,9756,-73.981923,9938,2015-02-03 14:10:00+00,2015-02-03 16:55:00+00,468,9696,40.765265,2023,E 55 St & Lexington Ave,40.759681,-73.970314,19070,Subscriber,1970.0,1
5,NaN,W 21 St & 6 Ave,NaN,15380,-73.994156,9807,2015-02-04 10:53:00+00,2015-02-04 13:36:00+00,435,15336,40.741740,435,W 21 St & 6 Ave,40.741740,-73.994156,18088,Subscriber,1985.0,1
6,NaN,Broadway & W 58 St,NaN,25241,-73.981693,9711,2015-02-05 11:12:00+00,2015-02-05 13:54:00+00,457,25203,40.766953,2021,W 45 St & 8 Ave,40.759291,-73.988597,14726,Subscriber,1962.0,1
7,NaN,Broadway & E 22 St,NaN,19952,-73.989551,9572,2015-02-04 19:09:00+00,2015-02-04 21:48:00+00,402,19897,40.740343,517,Pershing Square South,40.751581,-73.977910,14691,Subscriber,1966.0,2
8,NaN,Broadway & W 60 St,NaN,7139,-73.981918,9556,2015-02-02 13:25:00+00,2015-02-02 16:05:00+00,499,7073,40.769155,499,Broadway & W 60 St,40.769155,-73.981918,14802,Subscriber,1940.0,1
9,NaN,DeKalb Ave & Hudson Ave,NaN,11871,-73.981013,9373,2015-02-03 19:25:00+00,2015-02-03 22:01:00+00,324,11810,40.689888,324,DeKalb Ave & Hudson Ave,40.689888,-73.981013,15018,Subscriber,1968.0,1
10,NaN,E 11 St & 1 Ave,NaN,21495,-73.984267,9075,2015-02-04 22:46:00+00,2015-02-05 01:17:00+00,326,21438,40.729538,410,Suffolk St & Stanton St,40.720664,-73.985180,16119,Subscriber,1993.0,1
11,NaN,Broadway & W 24 St,NaN,39830,-73.989151,8705,2015-02-07 07:45:00+00,2015-02-07 10:10:00+00,444,39811,40.742354,444,Broadway & W 24 St,40.742354,-73.989151,16131,Customer,NaN,0
12,NaN,Broadway & W 24 St,NaN,39836,-73.989151,8548,2015-02-07 07:47:00+00,2015-02-07 10:10:00+00,444,39817,40.742354,444,Broadway & W 24 St,40.742354,-73.989151,15620,Customer,NaN,0
13,NaN,E 12 St & 3 Ave,NaN,21425,-73.988900,8470,2015-02-04 22:31:00+00,2015-02-05 00:52:00+00,483,21369,40.732233,311,Norfolk St & Broome St,40.717227,-73.988021,20201,Subscriber,1987.0,1
14,NaN,Barclay St & Church St,NaN,444,-74.010202,8376,2015-02-01 08:32:00+00,2015-02-01 10:52:00+00,417,376,40.712912,355,Bayard St & Baxter St,40.716021,-73.999744,16292,Subscriber,1950.0,2
15,NaN,Washington Ave & Park Ave,NaN,9053,-73.967510,8362,2015-02-03 10:10:00+00,2015-02-03 12:30:00+00,313,8992,40.696102,348,W Broadway & Spring St,40.724910,-74.001547,17690,Subscriber,1971.0,2
16,NaN,Barclay St & Church St,NaN,7553,-74.010202,8292,2015-02-02 18:29:00+00,2015-02-02 20:47:00+00,417,7486,40.712912,306,Cliff St & Fulton St,40.708235,-74.005301,14711,Subscriber,1972.0,1
17,NaN,Pershing Square North,NaN,34751,-73.977706,8254,2015-02-06 14:19:00+00,2015-02-06 16:37:00+00,519,34720,40.751873,501,FDR Drive & E 35 St,40.744219,-73.971212,21535,Subscriber,1950.0,2
18,NaN,Bialystoker Pl & Delancey St,NaN,42883,-73.982612,8002,2015-02-07 15:19:00+00,2015-02-07 17:32:00+00,356,42874,40.716226,326,E 11 St & 1 Ave,40.729538,-73.984267,20201,Subscriber,1987.0,1
19,NaN,Reade St & Broadway,NaN,12288,-74.005628,7990,2015-02-03 20:56:00+00,2015-02-03 23:10:00+00,330,12229,40.714505,386,Centre St & Worth St,40.714948,-74.002345,19732,Subscriber,1977.0,2
20,NaN,E 20 St & FDR Drive,NaN,376,-73.975739,7903,2015-02-01 08:00:00+00,2015-02-01 10:12:00+00,487,308,40.733143,331,Pike St & Monroe St,40.711731,-73.991930,20860,Subscriber,1991.0,1
21,NaN,Henry St & Grand St,NaN,758,-73.981346,7739,2015-02-01 09:58:00+00,2015-02-01 12:07:00+00,502,689,40.714215,293,Lafayette St & E 8 St,40.730287,-73.990765,17212,Subscriber,1966.0,1
22,NaN,West Thames St,NaN,3485,-74.017134,7649,2015-02-01 15:03:00+00,2015-02-01 17:10:00+00,363,3417,40.708347,426,West St & Chambers St,40.717548,-74.013221,18074,Subscriber,1983.0,1
23,NaN,Broadway & W 55 St,NaN,41914,-73.981923,7464,2015-02-07 13:30:00+00,2015-02-07 15:34:00+00,468,41904,40.765265,468,Broadway & W 55 St,40.765265,-73.981923,15214,Customer,NaN,0
24,NaN,South End Ave & Liberty St,NaN,1576,-74.015756,7225,2015-02-01 11:46:00+00,2015-02-01 13:47:00+00,3002,1506,40.711512,499,Broadway & W 60 St,40.769155,-73.981918,21202,Customer,NaN,0
25,NaN,Lafayette St & Jersey St,NaN,29895,-73.995653,7165,2015-02-05 19:36:00+00,2015-02-05 21:36:00+00,250,29852,40.724561,511,E 14 St & Avenue B,40.729387,-73.977724,16468,Subscriber,1986.0,1
26,NaN,E 11 St & 1 Ave,NaN,7158,-73.984267,7105,2015-02-02 13:41:00+00,2015-02-02 15:40:00+00,326,7092,40.729538,284,Greenwich Ave & 8 Ave,40.739017,-74.002638,16802,Subscriber,1969.0,1
27,NaN,E 52 St & 2 Ave,NaN,43961,-73.967416,7064,2015-02-07 17:09:00+00,2015-02-07 19:07:00+00,441,43954,40.756014,168,W 18 St & 6 Ave,40.739713,-73.994564,19830,Subscriber,1989.0,2
28,NaN,LaGuardia Pl & W 3 St,NaN,7879,-73.998102,6990,2015-02-02 21:55:00+00,2015-02-02 23:52:00+00,161,7812,40.729170,147,Greenwich St & Warren St,40.715422,-74.011220,18742,Subscriber,1969.0,1
29,NaN,E 17 St & Broadway,NaN,43083,-73.990093,6785,2015-02-07 15:42:00+00,2015-02-07 17:35:00+00,497,43075,40.737050,268,Howard St & Centre St,40.719105,-73.999733,19050,Customer,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46121,NaN,W 51 St & 6 Ave,NaN,10664,-73.980420,62,2015-02-03 17:09:00+00,2015-02-03 17:10:00+00,510,10603,40.760660,510,W 51 St & 6 Ave,40.760660,-73.980420,18740,Subscriber,1970.0,1
46122,NaN,W 21 St & 6 Ave,NaN,36216,-73.994156,62,2015-02-06 16:54:00+00,2015-02-06 16:55:00+00,435,36187,40.741740,435,W 21 St & 6 Ave,40.741740,-73.994156,21649,Subscriber,1961.0,1
46123,NaN,E 9 St & Avenue C,NaN,12980,-73.977688,62,2015-02-04 06:29:00+00,2015-02-04 06:30:00+00,394,12922,40.725213,394,E 9 St & Avenue C,40.725213,-73.977688,16107,Subscriber,1979.0,1
46124,NaN,Rivington St & Chrystie St,NaN,4929,-73.991925,62,2015-02-01 17:25:00+00,2015-02-01 17:26:00+00,473,4861,40.721101,473,Rivington St & Chrystie St,40.721101,-73.991925,16273,Subscriber,1980.0,2
46125,NaN,Broadway & W 51 St,NaN,39315,-73.983362,62,2015-02-06 23:06:00+00,2015-02-06 23:07:00+00,500,39290,40.762288,500,Broadway & W 51 St,40.762288,-73.983362,16531,Subscriber,1982.0,2
46126,NaN,LaGuardia Pl & W 3 St,NaN,4570,-73.998102,62,2015-02-01 16:52:00+00,2015-02-01 16:53:00+00,161,4501,40.729170,161,LaGuardia Pl & W 3 St,40.729170,-73.998102,20593,Subscriber,1987.0,1
46127,NaN,Bayard St & Baxter St,NaN,5781,-73.999744,61,2015-02-01 19:16:00+00,2015-02-01 19:17:00+00,355,5715,40.716021,355,Bayard St & Baxter St,40.716021,-73.999744,15079,Subscriber,1950.0,2
46128,NaN,Pershing Square South,NaN,9022,-73.977910,61,2015-02-03 10:02:00+00,2015-02-03 10:03:00+00,517,8962,40.751581,517,Pershing Square South,40.751581,-73.977910,19406,Subscriber,1976.0,1
46129,NaN,E 11 St & 2 Ave,NaN,11714,-73.986724,61,2015-02-03 19:01:00+00,2015-02-03 19:02:00+00,237,11653,40.730473,237,E 11 St & 2 Ave,40.730473,-73.986724,16900,Subscriber,1980.0,1
46130,NaN,W 26 St & 10 Ave,NaN,918,-74.002950,61,2015-02-01 10:26:00+00,2015-02-01 10:27:00+00,388,850,40.749718,388,W 26 St & 10 Ave,40.749718,-74.002950,15192,Subscriber,1983.0,1
46131,NaN,Mott St & Prince St,NaN,2639,-73.994800,61,2015-02-01 13:39:00+00,2015-02-01 13:40:00+00,251,2570,40.723180,251,Mott St & Prince St,40.723180,-73.994800,20381,Subscriber,1900.0,1
46132,NaN,Broadway & W 24 St,NaN,10683,-73.989151,61,2015-02-03 17:11:00+00,2015-02-03 17:12:00+00,444,10622,40.742354,444,Broadway & W 24 St,40.742354,-73.989151,19496,Subscriber,1986.0,1
46133,NaN,E 20 St & 2 Ave,NaN,6924,-73.982050,61,2015-02-02 10:05:00+00,2015-02-02 10:06:00+00,461,6858,40.735877,461,E 20 St & 2 Ave,40.735877,-73.982050,15005,Subscriber,1993.0,2
46134,NaN,E 24 St & Park Ave S,NaN,6999,-73.986022,61,2015-02-02 11:22:00+00,2015-02-02 11:23:00+00,491,6934,40.740964,491,E 24 St & Park Ave S,40.740964,-73.986022,17141,Subscriber,1970.0,1
46135,NaN,Forsyth St & Broome St,NaN,26953,-73.992663,61,2015-02-05 15:34:00+00,2015-02-05 15:35:00+00,531,26912,40.718939,531,Forsyth St & Broome St,40.718939,-73.992663,16247,Subscriber,1964.0,2
46136,NaN,Suffolk St & Stanton St,NaN,7618,-73.985180,61,2015-02-02 18:51:00+00,2015-02-02 18:52:00+00,410,7551,40.720664,410,Suffolk St & Stanton St,40.720664,-73.985180,15131,Subscriber,1984.0,1
46137,NaN,Mott St & Prince St,NaN,8347,-73.994800,60,2015-02-03 08:07:00+00,2015-02-03 08:08:00+00,251,8284,40.723180,251,Mott St & Prince St,40.723180,-73.994800,19896,Subscriber,1982.0,1
46138,NaN,Catherine St & Monroe St,NaN,24446,-73.996826,60,2015-02-05 09:32:00+00,2015-02-05 09:33:00+00,2009,24408,40.711174,2009,Catherine St & Monroe St,40.711174,-73.996826,18581,Subscriber,1983.0,1
46139,NaN,W 31 St & 7 Ave,NaN,7865,-73.991600,60,2015-02-02 21:39:00+00,2015-02-02 21:40:00+00,379,7798,40.749156,379,W 31 St & 7 Ave,40.749156,-73.991600,17643,Subscriber,1986.0,1
46140,NaN,W 29 St & 9 Ave,NaN,13533,-73.998393,60,2015-02-04 07:52:00+00,2015-02-04 07:53:00+00,512,13482,40.750073,512,W 29 St & 9 Ave,40.750073,-73.998393,21627,Subscriber,1960.0,2
46141,NaN,8 Ave & W 31 St,NaN,13098,-73.994811,60,2015-02-04 06:54:00+00,2015-02-04 06:55:00+00,521,13043,40.750450,521,8 Ave & W 31 St,40.750450,-73.994811,14788,Subscriber,1971.0,1
46142,NaN,Division St & Bowery,NaN,14163,-73.997047,60,2015-02-04 08:41:00+00,2015-02-04 08:42:00+00,296,14117,40.714131,296,Division St & Bowery,40.714131,-73.997047,21644,Subscriber,1990.0,1
46143,NaN,W 20 St & 8 Ave,NaN,33793,-74.000040,60,2015-02-06 11:38:00+00,2015-02-06 11:39:00+00,470,33759,40.743453,470,W 20 St & 8 Ave,40.743453,-74.000040,17448,Subscriber,1979.0,1
46144,NaN,E 10 St & Avenue A,NaN,38868,-73.981420,60,2015-02-06 20:40:00+00,2015-02-06 20:41:00+00,445,38842,40.727408,445,E 10 St & Avenue A,40.727408,-73.981420,16051,Subscriber,1987.0,1
46145,NaN,Grand St & Havemeyer St,NaN,11165,-73.956981,60,2015-02-03 18:01:00+00,2015-02-03 18:02:00+00,471,11104,40.712868,471,Grand St & Havemeyer St,40.712868,-73.956981,16340,Subscriber,1980.0,1
46146,NaN,W 38 St & 8 Ave,NaN,21463,-73.991382,60,2015-02-04 22:38:00+00,2015-02-04 22:39:00+00,523,21407,40.754666,523,W 38 St & 8 Ave,40.754666,-73.991382,16148,Subscriber,1980.0,1
46147,NaN,E 5 St & Avenue C,NaN,45697,-73.979955,60,2015-02-07 21:40:00+00,2015-02-07 21:41:00+00,393,45697,40.722992,393,E 5 St & Avenue C,40.722992,-73.979955,21524,Subscriber,1981.0,1
46148,NaN,E 6 St & Avenue B,NaN,3178,-73.981854,60,2015-02-01 14:34:00+00,2015-02-01 14:35:00+00,317,3110,40.724537,317,E 6 St & Avenue B,40.724537,-73.981854,20572,Subscriber,1985.0,1
46149,NaN,5 Ave & E 29 St,NaN,7364,-73.986831,60,2015-02-02 17:14:00+00,2015-02-02 17:15:00+00,474,7299,40.745168,474,5 Ave & E 29 St,40.745168,-73.986831,20842,Subscriber,1956.0,1
46150,NaN,Laight St & Hudson St,NaN,19295,-74.007718,60,2015-02-04 18:22:00+00,2015-02-04 18:23:00+00,248,19243,40.721854,248,Laight St & Hudson St,40.721854,-74.007718,20309,Subscriber,1970.0,1

**2. Only show the top/last 10 records( aka head and tail in SQL)**

In [13]:
test1_2 = '''
SELECT * 
FROM citibike
ORDER BY cartodb_id
LIMIT 10
;
'''
table = get_data(test1_2)
table

,the_geom,start_station_name,the_geom_webmercator,field_1,start_station_longitude,tripduration,starttime,stoptime,start_station_id,cartodb_id,start_station_latitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,NaN,8 Ave & W 31 St,NaN,70,-73.994811,801,2015-02-01 00:00:00+00,2015-02-01 00:14:00+00,521,1,40.750450,423,W 54 St & 9 Ave,40.765849,-73.986905,17131,Subscriber,1978,2
1,NaN,E 17 St & Broadway,NaN,71,-73.990093,379,2015-02-01 00:00:00+00,2015-02-01 00:07:00+00,497,2,40.737050,504,1 Ave & E 15 St,40.732219,-73.981656,21289,Subscriber,1993,1
2,NaN,Grand Army Plaza & Central Park S,NaN,72,-73.973715,2474,2015-02-01 00:01:00+00,2015-02-01 00:42:00+00,281,3,40.764397,127,Barrow St & Hudson St,40.731724,-74.006744,18903,Subscriber,1969,2
3,NaN,6 Ave & Broome St,NaN,73,-74.004704,818,2015-02-01 00:01:00+00,2015-02-01 00:15:00+00,2004,4,40.724399,505,6 Ave & W 33 St,40.749013,-73.988484,21044,Subscriber,1985,2
4,NaN,Lawrence St & Willoughby St,NaN,74,-73.986317,544,2015-02-01 00:01:00+00,2015-02-01 00:10:00+00,323,5,40.692362,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,19868,Subscriber,1957,1
5,NaN,Willoughby Ave & Walworth St,NaN,75,-73.953820,717,2015-02-01 00:02:00+00,2015-02-01 00:14:00+00,373,6,40.693317,2002,Wythe Ave & Metropolitan Ave,40.716887,-73.963198,15854,Subscriber,1979,1
6,NaN,W 56 St & 6 Ave,NaN,76,-73.977225,1306,2015-02-01 00:04:00+00,2015-02-01 00:26:00+00,352,7,40.763406,504,1 Ave & E 15 St,40.732219,-73.981656,15173,Subscriber,1983,1
7,NaN,E 4 St & 2 Ave,NaN,77,-73.989780,913,2015-02-01 00:04:00+00,2015-02-01 00:19:00+00,439,8,40.726281,116,W 17 St & 8 Ave,40.741776,-74.001497,17862,Subscriber,1955,1
8,NaN,Washington Pl & Broadway,NaN,78,-73.994046,759,2015-02-01 00:04:00+00,2015-02-01 00:17:00+00,335,9,40.729039,2012,E 27 St & 1 Ave,40.739445,-73.976806,21183,Subscriber,1985,2
9,NaN,Greenwich Ave & 8 Ave,NaN,79,-74.002638,585,2015-02-01 00:05:00+00,2015-02-01 00:15:00+00,284,10,40.739017,444,Broadway & W 24 St,40.742354,-73.989151,14843,Subscriber,1982,1

In [15]:
test1_2 = '''
SELECT * 
FROM citibike
ORDER BY birth_year DESC
LIMIT 10
;
'''
table = get_data(test1_2)
table

,the_geom,start_station_name,the_geom_webmercator,field_1,start_station_longitude,tripduration,starttime,stoptime,start_station_id,cartodb_id,start_station_latitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,NaN,E 15 St & 3 Ave,NaN,50,-73.986923,439,2015-02-07 03:43:00+00,2015-02-07 03:50:00+00,297,39651,40.734232,527,E 33 St & 2 Ave,40.744023,-73.976056,21448,Customer,NaN,0
1,NaN,E 48 St & 3 Ave,NaN,44,-73.971879,649,2015-02-06 16:09:00+00,2015-02-06 16:20:00+00,228,35656,40.754601,435,W 21 St & 6 Ave,40.741740,-73.994156,17160,Customer,NaN,0
2,NaN,W 20 St & 7 Ave,NaN,8,-73.997262,374,2015-02-01 17:48:00+00,2015-02-01 17:55:00+00,334,5067,40.742388,497,E 17 St & Broadway,40.737050,-73.990093,21456,Customer,NaN,0
3,NaN,W 4 St & 7 Ave S,NaN,18,-74.002939,3589,2015-02-03 19:55:00+00,2015-02-03 20:55:00+00,380,11966,40.734011,441,E 52 St & 2 Ave,40.756014,-73.967416,18079,Customer,NaN,0
4,NaN,6 Ave & W 33 St,NaN,43,-73.988484,1906,2015-02-06 14:12:00+00,2015-02-06 14:43:00+00,505,34660,40.749013,173,Broadway & W 49 St,40.760647,-73.984427,17348,Customer,NaN,0
5,NaN,Allen St & Hester St,NaN,7779,-73.991908,1217,2015-02-02 20:12:00+00,2015-02-02 20:32:00+00,361,7712,40.716059,461,E 20 St & 2 Ave,40.735877,-73.982050,19732,Customer,NaN,0
6,NaN,W 34 St & 11 Ave,NaN,42532,-74.002116,984,2015-02-07 14:42:00+00,2015-02-07 14:59:00+00,525,42523,40.755942,388,W 26 St & 10 Ave,40.749718,-74.002950,14549,Customer,NaN,0
7,NaN,E 12 St & 3 Ave,NaN,7,-73.988900,500,2015-02-01 17:38:00+00,2015-02-01 17:47:00+00,483,4983,40.732233,435,W 21 St & 6 Ave,40.741740,-73.994156,19409,Customer,NaN,0
8,NaN,W 41 St & 8 Ave,NaN,6156,-73.990026,240,2015-02-01 21:36:00+00,2015-02-01 21:40:00+00,477,6090,40.756405,490,8 Ave & W 33 St,40.751551,-73.993934,18266,Customer,NaN,0
9,NaN,E 47 St & 1 Ave,NaN,53,-73.967844,2049,2015-02-07 10:35:00+00,2015-02-07 11:09:00+00,516,40705,40.752069,484,W 44 St & 5 Ave,40.755003,-73.980144,21066,Customer,NaN,0

 ** 3. List all unique start_station_id values**

In [16]:
test1_3='''
SELECT DISTINCT start_station_id 
FROM citibike
ORDER BY start_station_id ASC
'''

table = get_data(test1_3)
table

     start_station_id  Unnamed: 1
0                  72         NaN
1                  79         NaN
2                  82         NaN
3                  83         NaN
4                 116         NaN
5                 119         NaN
6                 120         NaN
7                 127         NaN
8                 128         NaN
9                 137         NaN
10                143         NaN
11                144         NaN
12                146         NaN
13                147         NaN
14                150         NaN
15                151         NaN
16                152         NaN
17                153         NaN
18                157         NaN
19                160         NaN
20                161         NaN
21                164         NaN
22                167         NaN
23                168         NaN
24                173         NaN
25                174         NaN
26                195         NaN
27                212         NaN
28                216         NaN
29                217         NaN
..                ...         ...
297               525         NaN
298               526         NaN
299               527         NaN
300               528         NaN
301               529         NaN
302               530         NaN
303               531         NaN
304               532         NaN
305               533         NaN
306               534         NaN
307               537         NaN
308               538         NaN
309               539         NaN
310               545         NaN
311               546         NaN
312              2000         NaN
313              2001         NaN
314              2002         NaN
315              2004         NaN
316              2005         NaN
317              2006         NaN
318              2008         NaN
319              2009         NaN
320              2010         NaN
321              2012         NaN
322              2017         NaN
323              2021         NaN
324              2022         NaN
325              2023         NaN
326              3002         NaN

[327 rows x 2 columns]

 ** 4. Aggregation functions: 1. Count the number of trips (aka wc-l in SQL) 2. Find the average/min/maxtrip duration **

In [17]:
# 1. count the number of trips
test1_4 = '''
SELECT COUNT(start_station_id) as Number_Trips
FROM citibike
'''
table = get_data(test1_4)
table

   number_trips  Unnamed: 1
0         46200         NaN

In [18]:
#2. Find the average / min / max trip duration

test1_5 = '''
SELECT
avg(tripduration) as Avg_tripduration, min(tripduration) as Min_tripduration, Max(tripduration) as Max_tripduration
FROM citibike
'''

table = get_data(test1_5)
table

   avg_tripduration  min_tripduration  max_tripduration
0        675.865823                60             43016

# Task 2 - Working with date / time

**1.Selecting trips started on Feb-02-2015 only**

In [15]:
#  https://stackoverflow.com/questions/24192166/sql-server-how-to-select-records-with-specific-date-from-datetime-column
test2_1 = '''
SELECT * FROM citibike
WHERE starttime >='2015-02-02' and starttime<'2015-02-03';
'''
table2 = get_data(test2_1)
%time table2

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 7.15 Âµs

,the_geom,start_station_name,the_geom_webmercator,field_1,start_station_longitude,tripduration,starttime,stoptime,start_station_id,cartodb_id,start_station_latitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,NaN,5 Ave & E 29 St,NaN,7433,-73.986831,376,2015-02-02 17:44:00+00,2015-02-02 17:50:00+00,474,7367,40.745168,537,Lexington Ave & E 24 St,40.740259,-73.984092,18048,Subscriber,1977.0,1
1,NaN,Allen St & Hester St,NaN,7779,-73.991908,1217,2015-02-02 20:12:00+00,2015-02-02 20:32:00+00,361,7712,40.716059,461,E 20 St & 2 Ave,40.735877,-73.982050,19732,Customer,NaN,0
2,NaN,E 5 St & Avenue C,NaN,11,-73.979955,1312,2015-02-02 11:07:00+00,2015-02-02 11:29:00+00,393,6920,40.722992,476,E 31 St & 3 Ave,40.743943,-73.979661,17720,Subscriber,1955.0,1
3,NaN,9 Ave & W 16 St,NaN,627,-74.004432,444,2015-02-02 00:40:00+00,2015-02-02 00:48:00+00,463,6477,40.742065,489,10 Ave & W 28 St,40.750664,-74.001768,20233,Subscriber,1971.0,1
4,NaN,9 Ave & W 16 St,NaN,991,-74.004432,438,2015-02-02 00:40:00+00,2015-02-02 00:47:00+00,463,6478,40.742065,489,10 Ave & W 28 St,40.750664,-74.001768,20264,Subscriber,1981.0,2
5,NaN,W 33 St & 7 Ave,NaN,1037,-73.990931,498,2015-02-02 06:20:00+00,2015-02-02 06:28:00+00,492,6526,40.750200,493,W 45 St & 6 Ave,40.756800,-73.982912,16013,Subscriber,1962.0,2
6,NaN,W 27 St & 7 Ave,NaN,6510,-73.993915,199,2015-02-02 00:02:00+00,2015-02-02 00:05:00+00,442,6442,40.746647,489,10 Ave & W 28 St,40.750664,-74.001768,20684,Subscriber,1992.0,1
7,NaN,E 11 St & 1 Ave,NaN,6511,-73.984267,418,2015-02-02 00:03:00+00,2015-02-02 00:10:00+00,326,6443,40.729538,349,Rivington St & Ridge St,40.718502,-73.983299,16094,Subscriber,1964.0,2
8,NaN,Peck Slip & Front St,NaN,6512,-74.001670,276,2015-02-02 00:04:00+00,2015-02-02 00:09:00+00,279,6444,40.707873,415,Pearl St & Hanover Square,40.704718,-74.009260,17362,Subscriber,1974.0,1
9,NaN,E 16 St & 5 Ave,NaN,6513,-73.992390,420,2015-02-02 00:06:00+00,2015-02-02 00:13:00+00,496,6445,40.737262,237,E 11 St & 2 Ave,40.730473,-73.986724,15475,Subscriber,1992.0,2
10,NaN,W 41 St & 8 Ave,NaN,6514,-73.990026,304,2015-02-02 00:07:00+00,2015-02-02 00:12:00+00,477,6446,40.756405,450,W 49 St & 8 Ave,40.762272,-73.987882,16272,Subscriber,1968.0,1
11,NaN,Dean St & 4 Ave,NaN,6515,-73.978951,622,2015-02-02 00:08:00+00,2015-02-02 00:18:00+00,467,6447,40.683125,391,Clark St & Henry St,40.697601,-73.993446,16370,Subscriber,1979.0,1
12,NaN,9 Ave & W 18 St,NaN,6516,-74.003664,371,2015-02-02 00:09:00+00,2015-02-02 00:15:00+00,434,6448,40.743174,482,W 15 St & 7 Ave,40.739355,-73.999318,19437,Subscriber,1963.0,1
13,NaN,Reade St & Broadway,NaN,6517,-74.005628,477,2015-02-02 00:11:00+00,2015-02-02 00:19:00+00,330,6449,40.714505,2008,Little West St & 1 Pl,40.705693,-74.016777,21211,Subscriber,1982.0,1
14,NaN,8 Ave & W 31 St,NaN,6518,-73.994811,743,2015-02-02 00:12:00+00,2015-02-02 00:25:00+00,521,6450,40.750450,423,W 54 St & 9 Ave,40.765849,-73.986905,21417,Subscriber,1978.0,2
15,NaN,1 Ave & E 15 St,NaN,6519,-73.981656,599,2015-02-02 00:12:00+00,2015-02-02 00:22:00+00,504,6451,40.732219,453,W 22 St & 8 Ave,40.744751,-73.999154,15722,Subscriber,1956.0,1
16,NaN,Broadway & E 14 St,NaN,6520,-73.990741,345,2015-02-02 00:12:00+00,2015-02-02 00:18:00+00,285,6452,40.734546,236,St Marks Pl & 2 Ave,40.728419,-73.987140,18972,Subscriber,1962.0,1
17,NaN,E 2 St & Avenue B,NaN,6521,-73.983688,721,2015-02-02 00:13:00+00,2015-02-02 00:25:00+00,301,6453,40.722174,476,E 31 St & 3 Ave,40.743943,-73.979661,19628,Subscriber,1980.0,1
18,NaN,Peck Slip & Front St,NaN,6522,-74.001670,182,2015-02-02 00:13:00+00,2015-02-02 00:16:00+00,279,6454,40.707873,376,John St & William St,40.708621,-74.007222,15169,Subscriber,1978.0,1
19,NaN,Columbia St & Rivington St,NaN,6523,-73.980166,154,2015-02-02 00:13:00+00,2015-02-02 00:16:00+00,342,6455,40.717400,411,E 6 St & Avenue D,40.722281,-73.976687,17533,Subscriber,1997.0,1
20,NaN,W 20 St & 8 Ave,NaN,6524,-74.000040,435,2015-02-02 00:14:00+00,2015-02-02 00:21:00+00,470,6456,40.743453,491,E 24 St & Park Ave S,40.740964,-73.986022,19761,Subscriber,1983.0,1
21,NaN,St Marks Pl & 2 Ave,NaN,6525,-73.987140,310,2015-02-02 00:15:00+00,2015-02-02 00:20:00+00,236,6457,40.728419,393,E 5 St & Avenue C,40.722992,-73.979955,17267,Subscriber,1993.0,1
22,NaN,W 20 St & 8 Ave,NaN,6526,-74.000040,1274,2015-02-02 00:16:00+00,2015-02-02 00:37:00+00,470,6458,40.743453,470,W 20 St & 8 Ave,40.743453,-74.000040,18691,Subscriber,1964.0,1
23,NaN,W 37 St & 5 Ave,NaN,6527,-73.983390,642,2015-02-02 00:18:00+00,2015-02-02 00:29:00+00,485,6459,40.750380,174,E 25 St & 1 Ave,40.738177,-73.977387,17106,Subscriber,1977.0,1
24,NaN,W 13 St & 6 Ave,NaN,6528,-73.997044,256,2015-02-02 00:18:00+00,2015-02-02 00:22:00+00,345,6460,40.736494,483,E 12 St & 3 Ave,40.732233,-73.988900,20009,Subscriber,1973.0,1
25,NaN,10 Ave & W 28 St,NaN,6529,-74.001768,334,2015-02-02 00:19:00+00,2015-02-02 00:25:00+00,489,6461,40.750664,442,W 27 St & 7 Ave,40.746647,-73.993915,18777,Subscriber,1979.0,1
26,NaN,E 25 St & 2 Ave,NaN,6530,-73.979738,90,2015-02-02 00:19:00+00,2015-02-02 00:20:00+00,507,6462,40.739126,174,E 25 St & 1 Ave,40.738177,-73.977387,15357,Subscriber,1989.0,1
27,NaN,W 4 St & 7 Ave S,NaN,6531,-74.002939,203,2015-02-02 00:20:00+00,2015-02-02 00:23:00+00,380,6463,40.734011,405,Washington St & Gansevoort St,40.739323,-74.008119,18487,Subscriber,1983.0,1
28,NaN,W 20 St & 7 Ave,NaN,6532,-73.997262,649,2015-02-02 00:22:00+00,2015-02-02 00:32:00+00,334,6464,40.742388,439,E 4 St & 2 Ave,40.726281,-73.989780,20863,Subscriber,1981.0,1
29,NaN,W 46 St & 11 Ave,NaN,6533,-73.996674,319,2015-02-02 00:23:00+00,2015-02-02 00:29:00+00,508,6465,40.763414,448,W 37 St & 10 Ave,40.756604,-73.997901,16539,Subscriber,1970.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1429,NaN,Allen St & E Houston St,NaN,7938,-73.989111,722,2015-02-02 23:08:00+00,2015-02-02 23:20:00+00,312,7871,40.722055,380,W 4 St & 7 Ave S,40.734011,-74.002939,20572,Subscriber,1985.0,1
1430,NaN,Broadway & W 29 St,NaN,7939,-73.988557,274,2015-02-02 23:08:00+00,2015-02-02 23:12:00+00,486,7872,40.746201,491,E 24 St & Park Ave S,40.740964,-73.986022,20338,Subscriber,1981.0,1
1431,NaN,W 56 St & 6 Ave,NaN,7940,-73.977225,951,2015-02-02 23:11:00+00,2015-02-02 23:27:00+00,352,7873,40.763406,515,W 43 St & 10 Ave,40.760094,-73.994618,15826,Subscriber,1978.0,1
1432,NaN,10 Ave & W 28 St,NaN,7941,-74.001768,276,2015-02-02 23:16:00+00,2015-02-02 23:20:00+00,489,7874,40.750664,521,8 Ave & W 31 St,40.750450,-73.994811,18325,Subscriber,1990.0,1
1433,NaN,W 26 St & 8 Ave,NaN,7942,-73.997236,426,2015-02-02 23:17:00+00,2015-02-02 23:24:00+00,494,7875,40.747348,434,9 Ave & W 18 St,40.743174,-74.003664,16654,Subscriber,1977.0,1
1434,NaN,Broadway & E 22 St,NaN,7943,-73.989551,578,2015-02-02 23:19:00+00,2015-02-02 23:28:00+00,402,7876,40.740343,229,Great Jones St,40.727434,-73.993790,20902,Subscriber,1966.0,1
1435,NaN,E 47 St & 2 Ave,NaN,7944,-73.970325,2621,2015-02-02 23:22:00+00,2015-02-03 00:06:00+00,164,7877,40.753231,2017,E 43 St & 2 Ave,40.750224,-73.971214,20796,Subscriber,1954.0,1
1436,NaN,Broadway & W 32 St,NaN,7945,-73.988084,621,2015-02-02 23:22:00+00,2015-02-02 23:32:00+00,498,7878,40.748549,449,W 52 St & 9 Ave,40.764618,-73.987895,20160,Subscriber,1989.0,1
1437,NaN,8 Ave & W 31 St,NaN,7946,-73.994811,323,2015-02-02 23:23:00+00,2015-02-02 23:29:00+00,521,7879,40.750450,477,W 41 St & 8 Ave,40.756405,-73.990026,17392,Subscriber,1974.0,1
1438,NaN,9 Ave & W 18 St,NaN,7947,-74.003664,393,2015-02-02 23:24:00+00,2015-02-02 23:31:00+00,434,7880,40.743174,482,W 15 St & 7 Ave,40.739355,-73.999318,17263,Subscriber,1963.0,1
1439,NaN,LaGuardia Pl & W 3 St,NaN,7948,-73.998102,597,2015-02-02 23:25:00+00,2015-02-02 23:35:00+00,161,7881,40.729170,497,E 17 St & Broadway,40.737050,-73.990093,19858,Subscriber,1955.0,1
1440,NaN,W 26 St & 8 Ave,NaN,7949,-73.997236,244,2015-02-02 23:25:00+00,2015-02-02 23:30:00+00,494,7882,40.747348,462,W 22 St & 10 Ave,40.746920,-74.004519,20319,Subscriber,1979.0,1
1441,NaN,Cliff St & Fulton St,NaN,7950,-74.005301,1023,2015-02-02 23:26:00+00,2015-02-02 23:43:00+00,306,7883,40.708235,127,Barrow St & Hudson St,40.731724,-74.006744,21600,Subscriber,1977.0,1
1442,NaN,Rivington St & Ridge St,NaN,7951,-73.983299,419,2015-02-02 23:31:00+00,2015-02-02 23:38:00+00,349,7884,40.718502,473,Rivington St & Chrystie St,40.721101,-73.991925,18791,Subscriber,1986.0,1
1443,NaN,W 49 St & 8 Ave,NaN,7952,-73.987882,1429,2015-02-02 23:32:00+00,2015-02-02 23:55:00+00,450,7885,40.762272,358,Christopher St & Greenwich St,40.732916,-74.007114,17730,Subscriber,1966.0,1
1444,NaN,Pershing Square North,NaN,7953,-73.977706,676,2015-02-02 23:32:00+00,2015-02-02 23:44:00+00,519,7886,40.751873,477,W 41 St & 8 Ave,40.756405,-73.990026,18147,Subscriber,1980.0,1
1445,NaN,E 30 St & Park Ave S,NaN,7954,-73.983035,879,2015-02-02 23:33:00+00,2015-02-02 23:48:00+00,546,7887,40.744449,489,10 Ave & W 28 St,40.750664,-74.001768,20249,Subscriber,1959.0,1
1446,NaN,Sullivan St & Washington Sq,NaN,7955,-73.999061,593,2015-02-02 23:35:00+00,2015-02-02 23:45:00+00,336,7888,40.730477,432,E 7 St & Avenue A,40.726218,-73.983799,18078,Subscriber,1988.0,1
1447,NaN,W 42 St & 8 Ave,NaN,7956,-73.990985,839,2015-02-02 23:36:00+00,2015-02-02 23:50:00+00,529,7889,40.757570,164,E 47 St & 2 Ave,40.753231,-73.970325,16808,Subscriber,1983.0,1
1448,NaN,Broadway & E 22 St,NaN,7957,-73.989551,560,2015-02-02 23:37:00+00,2015-02-02 23:46:00+00,402,7890,40.740343,368,Carmine St & 6 Ave,40.730386,-74.002150,21355,Subscriber,1986.0,1
1449,NaN,1 Ave & E 15 St,NaN,7958,-73.981656,165,2015-02-02 23:37:00+00,2015-02-02 23:40:00+00,504,7891,40.732219,511,E 14 St & Avenue B,40.729387,-73.977724,15359,Subscriber,1994.0,1
1450,NaN,6 Ave & W 33 St,NaN,7959,-73.988484,813,2015-02-02 23:42:00+00,2015-02-02 23:56:00+00,505,7892,40.749013,489,10 Ave & W 28 St,40.750664,-74.001768,18250,Subscriber,1982.0,2
1451,NaN,9 Ave & W 22 St,NaN,7960,-74.001971,764,2015-02-02 23:42:00+00,2015-02-02 23:55:00+00,509,7893,40.745497,507,E 25 St & 2 Ave,40.739126,-73.979738,16969,Subscriber,1987.0,1
1452,NaN,E 16 St & 5 Ave,NaN,7961,-73.992390,2111,2015-02-02 23:43:00+00,2015-02-03 00:18:00+00,496,7894,40.737262,397,Fulton St & Clermont Ave,40.684157,-73.969223,18825,Subscriber,1979.0,1
1453,NaN,E 10 St & 5 Ave,NaN,7962,-73.995101,518,2015-02-02 23:43:00+00,2015-02-02 23:52:00+00,280,7895,40.733320,439,E 4 St & 2 Ave,40.726281,-73.989780,19000,Subscriber,1983.0,1
1454,NaN,W 44 St & 5 Ave,NaN,7963,-73.980144,371,2015-02-02 23:45:00+00,2015-02-02 23:52:00+00,484,7896,40.755003,440,E 45 St & 3 Ave,40.752554,-73.972826,20723,Subscriber,1977.0,1
1455,NaN,Spruce St & Nassau St,NaN,7964,-74.005524,188,2015-02-02 23:47:00+00,2015-02-02 23:50:00+00,224,7897,40.711464,417,Barclay St & Church St,40.712912,-74.010202,16528,Subscriber,1988.0,1
1456,NaN,W 13 St & 6 Ave,NaN,7965,-73.997044,689,2015-02-02 23:50:00+00,2015-02-03 00:02:00+00,345,7898,40.736494,394,E 9 St & Avenue C,40.725213,-73.977688,16541,Subscriber,1988.0,1
1457,NaN,W 22 St & 8 Ave,NaN,7966,-73.999154,634,2015-02-02 23:55:00+00,2015-02-03 00:05:00+00,453,7899,40.744751,537,Lexington Ave & E 24 St,40.740259,-73.984092,14878,Subscriber,1961.0,1
1458,NaN,Broadway & E 14 St,NaN,7967,-73.990741,733,2015-02-02 23:58:00+00,2015-02-03 00:10:00+00,285,7900,40.734546,302,Avenue D & E 3 St,40.720828,-73.977932,16326,Subscriber,1976.0,2

**2.Selecting trips started on the weekends - What are average trip during weekends**

In [16]:
test2_2 = '''
SELECT start_station_name,starttime,Avg(tripduration) as avg_trip
FROM citibike
WHERE EXTRACT(dow from starttime) in (0,6)
GROUP BY start_station_name,starttime
ORDER BY starttime ASC,avg_trip DESC;
'''

table2 = get_data(test2_2)
table2

                      start_station_name               starttime  avg_trip
0                        8 Ave & W 31 St  2015-02-01 00:00:00+00     801.0
1                     E 17 St & Broadway  2015-02-01 00:00:00+00     379.0
2      Grand Army Plaza & Central Park S  2015-02-01 00:01:00+00    2474.0
3                      6 Ave & Broome St  2015-02-01 00:01:00+00     818.0
4            Lawrence St & Willoughby St  2015-02-01 00:01:00+00     544.0
5           Willoughby Ave & Walworth St  2015-02-01 00:02:00+00     717.0
6                        W 56 St & 6 Ave  2015-02-01 00:04:00+00    1306.0
7                         E 4 St & 2 Ave  2015-02-01 00:04:00+00     913.0
8               Washington Pl & Broadway  2015-02-01 00:04:00+00     759.0
9                  Greenwich Ave & 8 Ave  2015-02-01 00:05:00+00     583.0
10                    Broadway & W 32 St  2015-02-01 00:05:00+00     204.0
11                    Carmine St & 6 Ave  2015-02-01 00:07:00+00    1169.0
12                       E 11 St & 1 Ave  2015-02-01 00:07:00+00     419.0
13                    Broadway & E 14 St  2015-02-01 00:09:00+00     527.0
14                    Carmine St & 6 Ave  2015-02-01 00:10:00+00    1013.0
15                     E 9 St & Avenue C  2015-02-01 00:13:00+00     587.0
16                       E 11 St & 1 Ave  2015-02-01 00:13:00+00     525.0
17                       W 45 St & 6 Ave  2015-02-01 00:14:00+00     670.0
18                    E 10 St & Avenue A  2015-02-01 00:15:00+00     711.0
19                        E 3 St & 1 Ave  2015-02-01 00:16:00+00    1559.0
20                       E 48 St & 3 Ave  2015-02-01 00:16:00+00     683.0
21                      W 56 St & 10 Ave  2015-02-01 00:16:00+00     522.0
22                       E 25 St & 2 Ave  2015-02-01 00:16:00+00     389.0
23                        E 4 St & 2 Ave  2015-02-01 00:16:00+00     276.0
24              MacDougal St & Prince St  2015-02-01 00:17:00+00     907.0
25                       8 Ave & W 33 St  2015-02-01 00:18:00+00     946.0
26                 Clinton St & Grand St  2015-02-01 00:18:00+00     144.0
27              Lafayette St & Jersey St  2015-02-01 00:19:00+00     257.0
28                       1 Ave & E 15 St  2015-02-01 00:20:00+00     602.0
29                     E 6 St & Avenue B  2015-02-01 00:21:00+00     764.0
...                                  ...                     ...       ...
12600              Barrow St & Hudson St  2015-02-07 23:49:00+00    1005.0
12601            Mercer St & Bleecker St  2015-02-07 23:49:00+00     278.0
12602           Washington Pl & Broadway  2015-02-07 23:51:00+00     812.0
12603               Allen St & Hester St  2015-02-07 23:51:00+00     647.0
12604              Warren St & Church St  2015-02-07 23:51:00+00     563.0
12605                    E 12 St & 3 Ave  2015-02-07 23:51:00+00     470.0
12606                    Dean St & 4 Ave  2015-02-07 23:51:00+00     299.0
12607               Allen St & Hester St  2015-02-07 23:52:00+00     629.0
12608                 Broadway & E 22 St  2015-02-07 23:52:00+00     499.0
12609              Washington Pl & 6 Ave  2015-02-07 23:52:00+00     474.0
12610                    E 31 St & 3 Ave  2015-02-07 23:52:00+00     345.0
12611                 Broadway & W 60 St  2015-02-07 23:53:00+00     829.0
12612                 Carmine St & 6 Ave  2015-02-07 23:53:00+00     776.0
12613                    W 52 St & 5 Ave  2015-02-07 23:53:00+00     697.0
12614                    Dean St & 4 Ave  2015-02-07 23:54:00+00    1703.0
12615                    9 Ave & W 45 St  2015-02-07 23:54:00+00     922.0
12616                 Broadway & W 58 St  2015-02-07 23:54:00+00     837.5
12617            Watts St & Greenwich St  2015-02-07 23:54:00+00     473.0
12618                    W 51 St & 6 Ave  2015-02-07 23:54:00+00     332.0
12619            University Pl & E 14 St  2015-02-07 23:55:00+00     456.0
12620                    W 11 St & 6 Ave  2015-02-07 23:55:00+00     327.0
12621                    W 17 St & 8 Ave  2015-02-07 23:55:00+00     306.0
12622                   W 47 St & 10 Ave  2015-02-07 23:56:00+00    1248.0
12623              Warren St & Church St  2015-02-07 23:56:00+00    1165.0
12624                    E 20 St & 2 Ave  2015-02-07 23:56:00+00     993.0
12625                    1 Ave & E 44 St  2015-02-07 23:57:00+00    1422.0
12626                    W 20 St & 8 Ave  2015-02-07 23:57:00+00     689.0
12627                    5 Ave & E 29 St  2015-02-07 23:57:00+00     410.0
12628                 Carmine St & 6 Ave  2015-02-07 23:58:00+00     548.0
12629                     E 4 St & 2 Ave  2015-02-07 23:59:00+00     917.0

[12630 rows x 3 columns]

**3.Selecting trips started on the weekday - What are average trip during weekends**

In [17]:
test2_3 = '''
SELECT start_station_name,starttime,Avg(tripduration) as avg_trip
FROM citibike
WHERE EXTRACT(dow from starttime) in (1,2,3,4,5)
GROUP BY start_station_name,starttime
ORDER BY starttime ASC,avg_trip DESC;
'''

table2 = get_data(test2_3)
table2

                   start_station_name               starttime  avg_trip
0                     W 27 St & 7 Ave  2015-02-02 00:02:00+00     199.0
1                     E 11 St & 1 Ave  2015-02-02 00:03:00+00     418.0
2                Peck Slip & Front St  2015-02-02 00:04:00+00     276.0
3                     E 16 St & 5 Ave  2015-02-02 00:06:00+00     420.0
4                     W 41 St & 8 Ave  2015-02-02 00:07:00+00     304.0
5                     Dean St & 4 Ave  2015-02-02 00:08:00+00     622.0
6                     9 Ave & W 18 St  2015-02-02 00:09:00+00     371.0
7                 Reade St & Broadway  2015-02-02 00:11:00+00     477.0
8                     8 Ave & W 31 St  2015-02-02 00:12:00+00     743.0
9                     1 Ave & E 15 St  2015-02-02 00:12:00+00     599.0
10                 Broadway & E 14 St  2015-02-02 00:12:00+00     345.0
11                  E 2 St & Avenue B  2015-02-02 00:13:00+00     721.0
12               Peck Slip & Front St  2015-02-02 00:13:00+00     182.0
13         Columbia St & Rivington St  2015-02-02 00:13:00+00     154.0
14                    W 20 St & 8 Ave  2015-02-02 00:14:00+00     435.0
15                St Marks Pl & 2 Ave  2015-02-02 00:15:00+00     310.0
16                    W 20 St & 8 Ave  2015-02-02 00:16:00+00    1274.0
17                    W 37 St & 5 Ave  2015-02-02 00:18:00+00     642.0
18                    W 13 St & 6 Ave  2015-02-02 00:18:00+00     256.0
19                   10 Ave & W 28 St  2015-02-02 00:19:00+00     334.0
20                    E 25 St & 2 Ave  2015-02-02 00:19:00+00      90.0
21                   W 4 St & 7 Ave S  2015-02-02 00:20:00+00     203.0
22                    W 20 St & 7 Ave  2015-02-02 00:22:00+00     649.0
23                   W 46 St & 11 Ave  2015-02-02 00:23:00+00     319.0
24                     E 3 St & 1 Ave  2015-02-02 00:27:00+00     154.0
25                Pike St & Monroe St  2015-02-02 00:28:00+00     550.0
26                    W 42 St & 8 Ave  2015-02-02 00:29:00+00     268.0
27            Clermont Ave & Park Ave  2015-02-02 00:29:00+00     153.0
28              Greenwich Ave & 8 Ave  2015-02-02 00:31:00+00     309.0
29         Greenwich Ave & Charles St  2015-02-02 00:33:00+00     138.0
...                               ...                     ...       ...
31851              Broadway & W 41 St  2015-02-06 23:47:00+00     321.0
31852                 W 38 St & 8 Ave  2015-02-06 23:48:00+00     449.0
31853                 9 Ave & W 22 St  2015-02-06 23:48:00+00     120.0
31854  Lafayette Ave & Fort Greene Pl  2015-02-06 23:49:00+00     977.0
31855              Broadway & E 22 St  2015-02-06 23:49:00+00     501.0
31856                 E 23 St & 1 Ave  2015-02-06 23:50:00+00     441.0
31857                 E 19 St & 3 Ave  2015-02-06 23:50:00+00     388.0
31858           Lafayette St & E 8 St  2015-02-06 23:51:00+00     607.0
31859              Broadway & E 22 St  2015-02-06 23:51:00+00     284.0
31860      Greenwich Ave & Charles St  2015-02-06 23:51:00+00     271.0
31861            Allen St & Hester St  2015-02-06 23:52:00+00     572.0
31862              E 20 St & Park Ave  2015-02-06 23:53:00+00     498.0
31863         DeKalb Ave & Hudson Ave  2015-02-06 23:53:00+00     425.0
31864                 E 16 St & 5 Ave  2015-02-06 23:53:00+00     267.0
31865                 W 44 St & 5 Ave  2015-02-06 23:53:00+00     165.0
31866                 E 56 St & 3 Ave  2015-02-06 23:54:00+00     751.0
31867               E 2 St & Avenue B  2015-02-06 23:54:00+00     747.0
31868                  E 4 St & 2 Ave  2015-02-06 23:54:00+00     511.0
31869              E 17 St & Broadway  2015-02-06 23:54:00+00     489.0
31870                 1 Ave & E 15 St  2015-02-06 23:55:00+00    1183.0
31871                 W 51 St & 6 Ave  2015-02-06 23:55:00+00     649.0
31872                 W 11 St & 6 Ave  2015-02-06 23:55:00+00     377.0
31873                 W 20 St & 8 Ave  2015-02-06 23:56:00+00     485.0
31874                 W 15 St & 7 Ave  2015-02-06 23:56:00+00     298.0
31875                 E 20 St & 2 Ave  2015-02-06 23:57:00+00     648.0
31876    MacDougal St & Washington Sq  2015-02-06 23:58:00+00    1261.0
31877         DeKalb Ave & Hudson Ave  2015-02-06 23:58:00+00     331.0
31878                 W 13 St & 6 Ave  2015-02-06 23:59:00+00     629.0
31879        Elizabeth St & Hester St  2015-02-06 23:59:00+00     492.0
31880         Allen St & Rivington St  2015-02-06 23:59:00+00     329.0

[31881 rows x 3 columns]

# Task 3 - Working with date / time

**1. Showing the list of start station locations  Using Group by**

In [18]:
test3_1 = '''
SELECT start_station_name
FROM citibike
GROUP BY start_station_name
'''
table3 = get_data(test3_1)
table3

                start_station_name  Unnamed: 1
0             E 30 St & Park Ave S         NaN
1          Pearl St & Anchorage Pl         NaN
2                  W 56 St & 6 Ave         NaN
3                   West Thames St         NaN
4          Bank St & Washington St         NaN
5                  8 Ave & W 52 St         NaN
6               E 11 St & Broadway         NaN
7         DeKalb Ave & Skillman St         NaN
8    Atlantic Ave & Fort Greene Pl         NaN
9                Avenue D & E 8 St         NaN
10            S 3 St & Bedford Ave         NaN
11          W Broadway & Spring St         NaN
12                 2 Ave & E 31 St         NaN
13                 E 33 St & 5 Ave         NaN
14        MacDougal St & Prince St         NaN
15    Clermont Ave & Lafayette Ave         NaN
16          Barclay St & Church St         NaN
17          Forsyth St & Broome St         NaN
18                 W 13 St & 6 Ave         NaN
19                 W 17 St & 8 Ave         NaN
20              E 20 St & Park Ave         NaN
21               E 2 St & Avenue B         NaN
22                 E 33 St & 2 Ave         NaN
23                 W 18 St & 6 Ave         NaN
24             Old Slip & Front St         NaN
25        Willoughby Ave & Hall St         NaN
26                 1 Ave & E 44 St         NaN
27                 W 20 St & 7 Ave         NaN
28           West St & Chambers St         NaN
29                 E 43 St & 2 Ave         NaN
..                             ...         ...
297               12 Ave & W 40 St         NaN
298        Centre St & Chambers St         NaN
299          Pershing Square South         NaN
300                W 33 St & 7 Ave         NaN
301         Hicks St & Montague St         NaN
302        University Pl & E 14 St         NaN
303        Fulton St & Rockwell Pl         NaN
304    Lafayette Ave & St James Pl         NaN
305        Emerson Pl & Myrtle Ave         NaN
306                E 56 St & 3 Ave         NaN
307        Watts St & Greenwich St         NaN
308                W 44 St & 5 Ave         NaN
309                6 Ave & W 33 St         NaN
310              E 9 St & Avenue C         NaN
311               11 Ave & W 59 St         NaN
312        W 16 St & The High Line         NaN
313          Howard St & Centre St         NaN
314                2 Ave & E 58 St         NaN
315              E 5 St & Avenue C         NaN
316       Fulton St & Clermont Ave         NaN
317    Cadman Plaza E & Tillary St         NaN
318      Pearl St & Hanover Square         NaN
319          LaGuardia Pl & W 3 St         NaN
320                5 Ave & E 29 St         NaN
321                W 21 St & 6 Ave         NaN
322   Wythe Ave & Metropolitan Ave         NaN
323                W 11 St & 6 Ave         NaN
324            St Marks Pl & 1 Ave         NaN
325                W 22 St & 8 Ave         NaN
326         Railroad Ave & Kay Ave         NaN

[327 rows x 2 columns]

**2. Showing the number of trips started per station**

In [19]:
test3_2 = '''
SELECT start_station_name,count(start_station_name) as Num_Trips
FROM citibike
GROUP BY start_station_name
ORDER BY Num_Trips DESC
'''

table3 = get_data(test3_2)
table3

                  start_station_name  num_trips
0                    8 Ave & W 31 St        530
1                    W 21 St & 6 Ave        519
2              Lafayette St & E 8 St        511
3                    W 41 St & 8 Ave        507
4           E 43 St & Vanderbilt Ave        486
5                 E 17 St & Broadway        455
6                    W 31 St & 7 Ave        424
7                    1 Ave & E 15 St        397
8                    8 Ave & W 33 St        387
9                 Broadway & E 14 St        373
10           Lexington Ave & E 24 St        372
11             Pershing Square South        362
12             Greenwich Ave & 8 Ave        342
13           University Pl & E 14 St        341
14                   W 18 St & 6 Ave        327
15                Broadway & E 22 St        324
16             Pershing Square North        323
17                   W 27 St & 7 Ave        320
18                Broadway & W 24 St        319
19                   E 33 St & 2 Ave        319
20                  W 20 St & 11 Ave        311
21                   W 33 St & 7 Ave        309
22                E 32 St & Park Ave        308
23                   2 Ave & E 31 St        302
24                   E 40 St & 5 Ave        298
25                   6 Ave & W 33 St        296
26                E 10 St & Avenue A        296
27                   E 20 St & 2 Ave        296
28                   W 24 St & 7 Ave        292
29     Christopher St & Greenwich St        292
..                               ...        ...
297      Cadman Plaza E & Tillary St         22
298      Washington Ave & Greene Ave         21
299       Myrtle Ave & St Edwards St         20
300          3 Ave & Schermerhorn St         19
301               Avenue D & E 12 St         19
302            Fulton St & Grand Ave         19
303               Front St & Gold St         19
304         Park Ave & St Edwards St         19
305          Macon St & Nostrand Ave         18
306             Henry St & Poplar St         18
307               Kent Ave & S 11 St         18
308    Cadman Plaza E & Red Cross Pl         18
309      Lexington Ave & Classon Ave         17
310       Clinton Ave & Flushing Ave         17
311  Cadman Plaza West & Montague St         16
312          Monroe St & Classon Ave         14
313                    Old Fulton St         14
314           Bedford Ave & S 9th St         13
315             S 3 St & Bedford Ave         13
316      Lafayette Ave & Classon Ave         13
317              Broadway & Berry St         12
318  Columbia Heights & Cranberry St         12
319         Hancock St & Bedford Ave         10
320         DeKalb Ave & Skillman St         10
321        Franklin Ave & Myrtle Ave          9
322              Nassau St & Navy St          7
323           Railroad Ave & Kay Ave          7
324      Gallatin Pl & Livingston St          7
325         Atlantic Ave & Furman St          5
326               Sands St & Navy St          4

[327 rows x 2 columns]

**3. Showing the number of trips started per station but only for station within 500m of Time Square! - The coordinates of Time Square is(40.7577,-73.9857)**

#### 1 degree of latitude in meter is 111000
#### 1 degree of lontitude in meter is 90000 meter
#### [https://gis.stackexchange.com/questions/142326/calculating-longitude-length-in-miles](https://gis.stackexchange.com/questions/142326/calculating-longitude-length-in-miles)

In [21]:
test3_3 = '''
SELECT start_station_id,start_station_name, count(start_station_name) as Num_Trips,
(SQRT(POWER((start_station_latitude - 40.7577)*111000,2)+POWER((start_station_longitude + 73.9857)*90000,2))) as dist
FROM citibike
WHERE (SQRT(POWER((start_station_latitude - 40.7577)*111000,2)+POWER((start_station_longitude + 73.9857)*90000,2)))<500
GROUP BY start_station_id,start_station_name,start_station_longitude,start_station_latitude
ORDER BY Num_Trips DESC;
'''

table3 = get_data(test3_3)
table3

   start_station_id  start_station_name  num_trips        dist
0               477     W 41 St & 8 Ave        507  415.026460
1               465  Broadway & W 41 St        251  295.472182
2               529     W 42 St & 8 Ave        221  475.875468
3               173  Broadway & W 49 St        213  346.590571
4               493     W 45 St & 6 Ave        141  270.110845
5              2021     W 45 St & 8 Ave        141  314.888014
6               524     W 43 St & 6 Ave        112  352.766327

# Task 4 - Putting it all together

** 1.â€¢ Find the station that had the longest average trip duration during
weekends and within 500m of TimeSquare! **

In [22]:
test4_1 = '''
SELECT start_station_name,starttime,Max(tripduration) as Max_tripduration, count(start_station_name) as Num_Trips,
(SQRT(POWER((start_station_latitude - 40.7577)*111000,2)+POWER((start_station_longitude + 73.9857)*90000,2))) as dist
FROM citibike
WHERE EXTRACT(dow from starttime) IN (0,6)
AND (SQRT(POWER((start_station_latitude - 40.7577)*111000,2)+POWER((start_station_longitude + 73.9857)*90000,2)))<500
GROUP BY start_station_name,starttime,start_station_longitude,start_station_latitude
ORDER BY Max_tripduration DESC
LIMIT 1;
'''

table4 = get_data(test4_1)
table4

,start_station_name,starttime,max_tripduration,num_trips,dist
0,Broadway & W 49 St,2015-02-07 17:23:00+00,15636,1,346.590571

** Extra: â€¢ create lines for trips started from stations within 500m of Times
Squares and lasted less than 2 hours. The number of trips per each
pair of stations are output as attributes of these lines.  **

In [23]:
# look back to the data
data.head(2)

,the_geom,start_station_name,the_geom_webmercator,field_1,start_station_longitude,tripduration,starttime,stoptime,start_station_id,cartodb_id,start_station_latitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,NaN,E 20 St & Park Ave,NaN,175,-73.987520,1090,2015-02-01 01:23:00+00,2015-02-01 01:42:00+00,503,107,40.738274,229,Great Jones St,40.727434,-73.993790,19718,Subscriber,1961.0,1
1,NaN,W 43 St & 10 Ave,NaN,1159,-73.994618,682,2015-02-01 10:55:00+00,2015-02-01 11:07:00+00,515,1088,40.760094,490,8 Ave & W 33 St,40.751551,-73.993934,21501,Subscriber,1981.0,1

In [24]:
## how to create a lines??

#1. select those trips started from station within 500m of Timess Square and lasted less than 2 hours

test5_1 = '''
SELECT start_station_id,start_station_name, tripduration, 
start_station_latitude,start_station_longitude,end_station_latitude,end_station_longitude,
(SQRT(POWER((start_station_latitude - 40.7577)*111000,2)+POWER((start_station_longitude + 73.9857)*90000,2))) as dist
FROM citibike
WHERE (SQRT(POWER((start_station_latitude - 40.7577)*111000,2)+POWER((start_station_longitude + 73.9857)*90000,2))) < 500 
AND tripduration < 7200
GROUP BY start_station_id,start_station_name,start_station_longitude,start_station_latitude,end_station_latitude,end_station_longitude,tripduration
ORDER BY start_station_id ASC,tripduration DESC;
'''

table5 = get_data(test5_1)
table5

,start_station_id,start_station_name,tripduration,start_station_latitude,start_station_longitude,end_station_latitude,end_station_longitude,dist
0,173,Broadway & W 49 St,2797,40.760647,-73.984427,40.762288,-73.983362,346.590571
1,173,Broadway & W 49 St,2492,40.760647,-73.984427,40.708621,-74.007222,346.590571
2,173,Broadway & W 49 St,2338,40.760647,-73.984427,40.765265,-73.981923,346.590571
3,173,Broadway & W 49 St,1823,40.760647,-73.984427,40.711512,-74.015756,346.590571
4,173,Broadway & W 49 St,1653,40.760647,-73.984427,40.735238,-74.000271,346.590571
5,173,Broadway & W 49 St,1533,40.760647,-73.984427,40.760647,-73.984427,346.590571
6,173,Broadway & W 49 St,1418,40.760647,-73.984427,40.739713,-73.994564,346.590571
7,173,Broadway & W 49 St,1396,40.760647,-73.984427,40.727791,-73.985649,346.590571
8,173,Broadway & W 49 St,1377,40.760647,-73.984427,40.739713,-73.994564,346.590571
9,173,Broadway & W 49 St,1346,40.760647,-73.984427,40.736245,-73.984738,346.590571
10,173,Broadway & W 49 St,1328,40.760647,-73.984427,40.747348,-73.997236,346.590571
11,173,Broadway & W 49 St,1319,40.760647,-73.984427,40.739445,-73.976806,346.590571
12,173,Broadway & W 49 St,1251,40.760647,-73.984427,40.756800,-73.982912,346.590571
13,173,Broadway & W 49 St,1195,40.760647,-73.984427,40.732219,-73.981656,346.590571
14,173,Broadway & W 49 St,1167,40.760647,-73.984427,40.728145,-73.990214,346.590571
15,173,Broadway & W 49 St,1155,40.760647,-73.984427,40.744023,-73.976056,346.590571
16,173,Broadway & W 49 St,1148,40.760647,-73.984427,40.737050,-73.990093,346.590571
17,173,Broadway & W 49 St,1142,40.760647,-73.984427,40.746745,-74.007756,346.590571
18,173,Broadway & W 49 St,1136,40.760647,-73.984427,40.760094,-73.994618,346.590571
19,173,Broadway & W 49 St,1124,40.760647,-73.984427,40.747659,-73.984907,346.590571
20,173,Broadway & W 49 St,1080,40.760647,-73.984427,40.741740,-73.994156,346.590571
21,173,Broadway & W 49 St,1016,40.760647,-73.984427,40.756604,-73.997901,346.590571
22,173,Broadway & W 49 St,984,40.760647,-73.984427,40.740259,-73.984092,346.590571
23,173,Broadway & W 49 St,975,40.760647,-73.984427,40.744023,-73.976056,346.590571
24,173,Broadway & W 49 St,955,40.760647,-73.984427,40.746920,-74.004519,346.590571
25,173,Broadway & W 49 St,944,40.760647,-73.984427,40.746920,-74.004519,346.590571
26,173,Broadway & W 49 St,919,40.760647,-73.984427,40.746920,-74.004519,346.590571
27,173,Broadway & W 49 St,917,40.760647,-73.984427,40.753231,-73.970325,346.590571
28,173,Broadway & W 49 St,896,40.760647,-73.984427,40.746745,-74.007756,346.590571
29,173,Broadway & W 49 St,888,40.760647,-73.984427,40.740343,-73.989551,346.590571
...,...,...,...,...,...,...,...,...
1539,2021,W 45 St & 8 Ave,334,40.759291,-73.988597,40.750200,-73.990931,314.888014
1540,2021,W 45 St & 8 Ave,323,40.759291,-73.988597,40.751551,-73.993934,314.888014
1541,2021,W 45 St & 8 Ave,318,40.759291,-73.988597,40.760660,-73.980420,314.888014
1542,2021,W 45 St & 8 Ave,311,40.759291,-73.988597,40.763707,-73.985162,314.888014
1543,2021,W 45 St & 8 Ave,274,40.759291,-73.988597,40.763707,-73.985162,314.888014
1544,2021,W 45 St & 8 Ave,271,40.759291,-73.988597,40.760094,-73.994618,314.888014
1545,2021,W 45 St & 8 Ave,267,40.759291,-73.988597,40.763707,-73.985162,314.888014
1546,2021,W 45 St & 8 Ave,260,40.759291,-73.988597,40.757570,-73.990985,314.888014
1547,2021,W 45 St & 8 Ave,260,40.759291,-73.988597,40.760301,-73.998842,314.888014
1548,2021,W 45 St & 8 Ave,246,40.759291,-73.988597,40.755136,-73.986580,314.888014
1549,2021,W 45 St & 8 Ave,246,40.759291,-73.988597,40.763707,-73.985162,314.888014
1550,2021,W 45 St & 8 Ave,238,40.759291,-73.988597,40.762699,-73.993012,314.888014
1551,2021,W 45 St & 8 Ave,228,40.759291,-73.988597,40.763707,-73.985162,314.888014
1552,2021,W 45 St & 8 Ave,224,40.759291,-73.988597,40.762699,-73.993012,314.888014
1553,2021,W 45 St & 8 Ave,218,40.759291,-73.988597,40.763707,-73.985162,314.888014
1554,2021,W 45 St & 8 Ave,218,40.759291,-73.988597,40.755136,-73.986580,314.888014
1555,2021,W 45 St & 8 Ave,218,40.759291,-73.988597,40.760094,-73.994618,314.888014
1556,2021,W 45 St & 8 Ave,216,40.759291,-73.988597,40.756458,-73.993722,314.888014
1557,2021,W 45 St & 8 Ave,207,40.759291,-73.988597,40.760647,-73.984427,314.888014
1558,2021,W 45 St & 8 Ave,205,40.759291,-73.988597,40.756458,-73.993722,314.888014
1559,2021,W 45 St & 8 Ave,202,40.759291,-73.988597,40.763707,-73.985162,314.888014
1560,2021,W 45 St & 8 Ave,197,40.759291,-73.988597,40.756458,-73.993722,314.888014
1561,2021,W 45 St & 8 Ave,188,40.759291,-73.988597,40.763707,-73.985162,314.888014
1562,2021,W 45 St & 8 Ave,180,40.759291,-73.988597,40.760094,-73.994618,314.888014
1563,2021,W 45 St & 8 Ave,178,40.759291,-73.988597,40.763707,-73.985162,314.888014
1564,2021,W 45 St & 8 Ave,162,40.759291,-73.988597,40.759291,-73.988597,314.888014
1565,2021,W 45 St & 8 Ave,141,40.759291,-73.988597,40.762699,-73.993012,314.888014
1566,2021,W 45 St & 8 Ave,123,40.759291,-73.988597,40.759291,-73.988597,314.888014
1567,2021,W 45 St & 8 Ave,112,40.759291,-73.988597,40.760193,-73.991255,314.888014
1568,2021,W 45 St & 8 Ave,90,40.759291,-73.988597,40.759291,-73.988597,314.888014